# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AllowanceInfoType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, invoice_date: datetime=None):  # noqa: E501
        """AllowanceInfoType - a model defined in Swagger

        :param invoice_date: The invoice_date of this AllowanceInfoType.  # noqa: E501
        :type invoice_date: datetime
        """
        self.swagger_types = {
            'invoice_date': datetime
        }

        self.attribute_map = {
            'invoice_date': 'invoiceDate'
        }
        self._invoice_date = invoice_date

    @classmethod
    def from_dict(cls, dikt) -> 'AllowanceInfoType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllowanceInfoType of this AllowanceInfoType.  # noqa: E501
        :rtype: AllowanceInfoType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def invoice_date(self) -> datetime:
        """Gets the invoice_date of this AllowanceInfoType.


        :return: The invoice_date of this AllowanceInfoType.
        :rtype: datetime
        """
        return self._invoice_date

    @invoice_date.setter
    def invoice_date(self, invoice_date: datetime):
        """Sets the invoice_date of this AllowanceInfoType.


        :param invoice_date: The invoice_date of this AllowanceInfoType.
        :type invoice_date: datetime
        """

        self._invoice_date = invoice_date
