# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AmountType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, amount: float=None, currency_id: str=None):  # noqa: E501
        """AmountType - a model defined in Swagger

        :param amount: The amount of this AmountType.  # noqa: E501
        :type amount: float
        :param currency_id: The currency_id of this AmountType.  # noqa: E501
        :type currency_id: str
        """
        self.swagger_types = {
            'amount': float,
            'currency_id': str
        }

        self.attribute_map = {
            'amount': 'amount',
            'currency_id': 'currencyId'
        }
        self._amount = amount
        self._currency_id = currency_id

    @classmethod
    def from_dict(cls, dikt) -> 'AmountType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AmountType of this AmountType.  # noqa: E501
        :rtype: AmountType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amount(self) -> float:
        """Gets the amount of this AmountType.


        :return: The amount of this AmountType.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount: float):
        """Sets the amount of this AmountType.


        :param amount: The amount of this AmountType.
        :type amount: float
        """

        self._amount = amount

    @property
    def currency_id(self) -> str:
        """Gets the currency_id of this AmountType.


        :return: The currency_id of this AmountType.
        :rtype: str
        """
        return self._currency_id

    @currency_id.setter
    def currency_id(self, currency_id: str):
        """Sets the currency_id of this AmountType.


        :param currency_id: The currency_id of this AmountType.
        :type currency_id: str
        """

        self._currency_id = currency_id
