# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.batch_note_type import BatchNoteType  # noqa: F401,E501
from swagger_server import util


class BatchTypeNotes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, note: List[BatchNoteType]=None):  # noqa: E501
        """BatchTypeNotes - a model defined in Swagger

        :param note: The note of this BatchTypeNotes.  # noqa: E501
        :type note: List[BatchNoteType]
        """
        self.swagger_types = {
            'note': List[BatchNoteType]
        }

        self.attribute_map = {
            'note': 'note'
        }
        self._note = note

    @classmethod
    def from_dict(cls, dikt) -> 'BatchTypeNotes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BatchType_notes of this BatchTypeNotes.  # noqa: E501
        :rtype: BatchTypeNotes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def note(self) -> List[BatchNoteType]:
        """Gets the note of this BatchTypeNotes.


        :return: The note of this BatchTypeNotes.
        :rtype: List[BatchNoteType]
        """
        return self._note

    @note.setter
    def note(self, note: List[BatchNoteType]):
        """Sets the note of this BatchTypeNotes.


        :param note: The note of this BatchTypeNotes.
        :type note: List[BatchNoteType]
        """

        self._note = note
