# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CancelInvoiceCBMType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, invoice_nbr: List[str]=None):  # noqa: E501
        """CancelInvoiceCBMType - a model defined in Swagger

        :param invoice_nbr: The invoice_nbr of this CancelInvoiceCBMType.  # noqa: E501
        :type invoice_nbr: List[str]
        """
        self.swagger_types = {
            'invoice_nbr': List[str]
        }

        self.attribute_map = {
            'invoice_nbr': 'invoiceNbr'
        }
        self._invoice_nbr = invoice_nbr

    @classmethod
    def from_dict(cls, dikt) -> 'CancelInvoiceCBMType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CancelInvoiceCBMType of this CancelInvoiceCBMType.  # noqa: E501
        :rtype: CancelInvoiceCBMType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def invoice_nbr(self) -> List[str]:
        """Gets the invoice_nbr of this CancelInvoiceCBMType.


        :return: The invoice_nbr of this CancelInvoiceCBMType.
        :rtype: List[str]
        """
        return self._invoice_nbr

    @invoice_nbr.setter
    def invoice_nbr(self, invoice_nbr: List[str]):
        """Sets the invoice_nbr of this CancelInvoiceCBMType.


        :param invoice_nbr: The invoice_nbr of this CancelInvoiceCBMType.
        :type invoice_nbr: List[str]
        """
        if invoice_nbr is None:
            raise ValueError("Invalid value for `invoice_nbr`, must not be `None`")  # noqa: E501

        self._invoice_nbr = invoice_nbr
