# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.note_type import NoteType  # noqa: F401,E501
from swagger_server import util


class ClaimNoteType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, note_type: NoteType=None, predefined_text_id: str=None, creation_date: datetime=None, creation_user_id: str=None):  # noqa: E501
        """ClaimNoteType - a model defined in Swagger

        :param note_type: The note_type of this ClaimNoteType.  # noqa: E501
        :type note_type: NoteType
        :param predefined_text_id: The predefined_text_id of this ClaimNoteType.  # noqa: E501
        :type predefined_text_id: str
        :param creation_date: The creation_date of this ClaimNoteType.  # noqa: E501
        :type creation_date: datetime
        :param creation_user_id: The creation_user_id of this ClaimNoteType.  # noqa: E501
        :type creation_user_id: str
        """
        self.swagger_types = {
            'note_type': NoteType,
            'predefined_text_id': str,
            'creation_date': datetime,
            'creation_user_id': str
        }

        self.attribute_map = {
            'note_type': 'noteType',
            'predefined_text_id': 'predefinedTextId',
            'creation_date': 'creationDate',
            'creation_user_id': 'creationUserId'
        }
        self._note_type = note_type
        self._predefined_text_id = predefined_text_id
        self._creation_date = creation_date
        self._creation_user_id = creation_user_id

    @classmethod
    def from_dict(cls, dikt) -> 'ClaimNoteType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClaimNoteType of this ClaimNoteType.  # noqa: E501
        :rtype: ClaimNoteType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def note_type(self) -> NoteType:
        """Gets the note_type of this ClaimNoteType.


        :return: The note_type of this ClaimNoteType.
        :rtype: NoteType
        """
        return self._note_type

    @note_type.setter
    def note_type(self, note_type: NoteType):
        """Sets the note_type of this ClaimNoteType.


        :param note_type: The note_type of this ClaimNoteType.
        :type note_type: NoteType
        """

        self._note_type = note_type

    @property
    def predefined_text_id(self) -> str:
        """Gets the predefined_text_id of this ClaimNoteType.


        :return: The predefined_text_id of this ClaimNoteType.
        :rtype: str
        """
        return self._predefined_text_id

    @predefined_text_id.setter
    def predefined_text_id(self, predefined_text_id: str):
        """Sets the predefined_text_id of this ClaimNoteType.


        :param predefined_text_id: The predefined_text_id of this ClaimNoteType.
        :type predefined_text_id: str
        """

        self._predefined_text_id = predefined_text_id

    @property
    def creation_date(self) -> datetime:
        """Gets the creation_date of this ClaimNoteType.


        :return: The creation_date of this ClaimNoteType.
        :rtype: datetime
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date: datetime):
        """Sets the creation_date of this ClaimNoteType.


        :param creation_date: The creation_date of this ClaimNoteType.
        :type creation_date: datetime
        """

        self._creation_date = creation_date

    @property
    def creation_user_id(self) -> str:
        """Gets the creation_user_id of this ClaimNoteType.


        :return: The creation_user_id of this ClaimNoteType.
        :rtype: str
        """
        return self._creation_user_id

    @creation_user_id.setter
    def creation_user_id(self, creation_user_id: str):
        """Sets the creation_user_id of this ClaimNoteType.


        :param creation_user_id: The creation_user_id of this ClaimNoteType.
        :type creation_user_id: str
        """

        self._creation_user_id = creation_user_id
