# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ClaimTypeIncidents(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, incident_nbr: List[int]=None):  # noqa: E501
        """ClaimTypeIncidents - a model defined in Swagger

        :param incident_nbr: The incident_nbr of this ClaimTypeIncidents.  # noqa: E501
        :type incident_nbr: List[int]
        """
        self.swagger_types = {
            'incident_nbr': List[int]
        }

        self.attribute_map = {
            'incident_nbr': 'incidentNbr'
        }
        self._incident_nbr = incident_nbr

    @classmethod
    def from_dict(cls, dikt) -> 'ClaimTypeIncidents':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClaimType_incidents of this ClaimTypeIncidents.  # noqa: E501
        :rtype: ClaimTypeIncidents
        """
        return util.deserialize_model(dikt, cls)

    @property
    def incident_nbr(self) -> List[int]:
        """Gets the incident_nbr of this ClaimTypeIncidents.


        :return: The incident_nbr of this ClaimTypeIncidents.
        :rtype: List[int]
        """
        return self._incident_nbr

    @incident_nbr.setter
    def incident_nbr(self, incident_nbr: List[int]):
        """Sets the incident_nbr of this ClaimTypeIncidents.


        :param incident_nbr: The incident_nbr of this ClaimTypeIncidents.
        :type incident_nbr: List[int]
        """

        self._incident_nbr = incident_nbr
