# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.history_modification_type import HistoryModificationType  # noqa: F401,E501
from swagger_server import util


class ClaimTypeHistoryModifications(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, history_modification: List[HistoryModificationType]=None):  # noqa: E501
        """ClaimTypeHistoryModifications - a model defined in Swagger

        :param history_modification: The history_modification of this ClaimTypeHistoryModifications.  # noqa: E501
        :type history_modification: List[HistoryModificationType]
        """
        self.swagger_types = {
            'history_modification': List[HistoryModificationType]
        }

        self.attribute_map = {
            'history_modification': 'historyModification'
        }
        self._history_modification = history_modification

    @classmethod
    def from_dict(cls, dikt) -> 'ClaimTypeHistoryModifications':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClaimType_historyModifications of this ClaimTypeHistoryModifications.  # noqa: E501
        :rtype: ClaimTypeHistoryModifications
        """
        return util.deserialize_model(dikt, cls)

    @property
    def history_modification(self) -> List[HistoryModificationType]:
        """Gets the history_modification of this ClaimTypeHistoryModifications.


        :return: The history_modification of this ClaimTypeHistoryModifications.
        :rtype: List[HistoryModificationType]
        """
        return self._history_modification

    @history_modification.setter
    def history_modification(self, history_modification: List[HistoryModificationType]):
        """Sets the history_modification of this ClaimTypeHistoryModifications.


        :param history_modification: The history_modification of this ClaimTypeHistoryModifications.
        :type history_modification: List[HistoryModificationType]
        """

        self._history_modification = history_modification
