# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ClaimTypeInvoices(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, invoice_nbr: List[int]=None):  # noqa: E501
        """ClaimTypeInvoices - a model defined in Swagger

        :param invoice_nbr: The invoice_nbr of this ClaimTypeInvoices.  # noqa: E501
        :type invoice_nbr: List[int]
        """
        self.swagger_types = {
            'invoice_nbr': List[int]
        }

        self.attribute_map = {
            'invoice_nbr': 'invoiceNbr'
        }
        self._invoice_nbr = invoice_nbr

    @classmethod
    def from_dict(cls, dikt) -> 'ClaimTypeInvoices':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClaimType_invoices of this ClaimTypeInvoices.  # noqa: E501
        :rtype: ClaimTypeInvoices
        """
        return util.deserialize_model(dikt, cls)

    @property
    def invoice_nbr(self) -> List[int]:
        """Gets the invoice_nbr of this ClaimTypeInvoices.


        :return: The invoice_nbr of this ClaimTypeInvoices.
        :rtype: List[int]
        """
        return self._invoice_nbr

    @invoice_nbr.setter
    def invoice_nbr(self, invoice_nbr: List[int]):
        """Sets the invoice_nbr of this ClaimTypeInvoices.


        :param invoice_nbr: The invoice_nbr of this ClaimTypeInvoices.
        :type invoice_nbr: List[int]
        """

        self._invoice_nbr = invoice_nbr
