# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.close_claim_cbm_type_claims import CloseClaimCBMTypeClaims  # noqa: F401,E501
from swagger_server.models.perform_action_type import PerformActionType  # noqa: F401,E501
from swagger_server.models.queue_item_type import QueueItemType  # noqa: F401,E501
from swagger_server import util


class ClaimStatusItemType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, queue_item: QueueItemType=None, perform_action: PerformActionType=None, claims: CloseClaimCBMTypeClaims=None):  # noqa: E501
        """ClaimStatusItemType - a model defined in Swagger

        :param queue_item: The queue_item of this ClaimStatusItemType.  # noqa: E501
        :type queue_item: QueueItemType
        :param perform_action: The perform_action of this ClaimStatusItemType.  # noqa: E501
        :type perform_action: PerformActionType
        :param claims: The claims of this ClaimStatusItemType.  # noqa: E501
        :type claims: CloseClaimCBMTypeClaims
        """
        self.swagger_types = {
            'queue_item': QueueItemType,
            'perform_action': PerformActionType,
            'claims': CloseClaimCBMTypeClaims
        }

        self.attribute_map = {
            'queue_item': 'queueItem',
            'perform_action': 'performAction',
            'claims': 'claims'
        }
        self._queue_item = queue_item
        self._perform_action = perform_action
        self._claims = claims

    @classmethod
    def from_dict(cls, dikt) -> 'ClaimStatusItemType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClaimStatusItemType of this ClaimStatusItemType.  # noqa: E501
        :rtype: ClaimStatusItemType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def queue_item(self) -> QueueItemType:
        """Gets the queue_item of this ClaimStatusItemType.


        :return: The queue_item of this ClaimStatusItemType.
        :rtype: QueueItemType
        """
        return self._queue_item

    @queue_item.setter
    def queue_item(self, queue_item: QueueItemType):
        """Sets the queue_item of this ClaimStatusItemType.


        :param queue_item: The queue_item of this ClaimStatusItemType.
        :type queue_item: QueueItemType
        """
        if queue_item is None:
            raise ValueError("Invalid value for `queue_item`, must not be `None`")  # noqa: E501

        self._queue_item = queue_item

    @property
    def perform_action(self) -> PerformActionType:
        """Gets the perform_action of this ClaimStatusItemType.


        :return: The perform_action of this ClaimStatusItemType.
        :rtype: PerformActionType
        """
        return self._perform_action

    @perform_action.setter
    def perform_action(self, perform_action: PerformActionType):
        """Sets the perform_action of this ClaimStatusItemType.


        :param perform_action: The perform_action of this ClaimStatusItemType.
        :type perform_action: PerformActionType
        """
        if perform_action is None:
            raise ValueError("Invalid value for `perform_action`, must not be `None`")  # noqa: E501

        self._perform_action = perform_action

    @property
    def claims(self) -> CloseClaimCBMTypeClaims:
        """Gets the claims of this ClaimStatusItemType.


        :return: The claims of this ClaimStatusItemType.
        :rtype: CloseClaimCBMTypeClaims
        """
        return self._claims

    @claims.setter
    def claims(self, claims: CloseClaimCBMTypeClaims):
        """Sets the claims of this ClaimStatusItemType.


        :param claims: The claims of this ClaimStatusItemType.
        :type claims: CloseClaimCBMTypeClaims
        """
        if claims is None:
            raise ValueError("Invalid value for `claims`, must not be `None`")  # noqa: E501

        self._claims = claims
