# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.reserve_detail_type import ReserveDetailType  # noqa: F401,E501
from swagger_server import util


class ClaimReserveItemInfoTypeReserveDetails(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, reserve_detail: List[ReserveDetailType]=None):  # noqa: E501
        """ClaimReserveItemInfoTypeReserveDetails - a model defined in Swagger

        :param reserve_detail: The reserve_detail of this ClaimReserveItemInfoTypeReserveDetails.  # noqa: E501
        :type reserve_detail: List[ReserveDetailType]
        """
        self.swagger_types = {
            'reserve_detail': List[ReserveDetailType]
        }

        self.attribute_map = {
            'reserve_detail': 'reserveDetail'
        }
        self._reserve_detail = reserve_detail

    @classmethod
    def from_dict(cls, dikt) -> 'ClaimReserveItemInfoTypeReserveDetails':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClaimReserveItemInfoType_reserveDetails of this ClaimReserveItemInfoTypeReserveDetails.  # noqa: E501
        :rtype: ClaimReserveItemInfoTypeReserveDetails
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reserve_detail(self) -> List[ReserveDetailType]:
        """Gets the reserve_detail of this ClaimReserveItemInfoTypeReserveDetails.


        :return: The reserve_detail of this ClaimReserveItemInfoTypeReserveDetails.
        :rtype: List[ReserveDetailType]
        """
        return self._reserve_detail

    @reserve_detail.setter
    def reserve_detail(self, reserve_detail: List[ReserveDetailType]):
        """Sets the reserve_detail of this ClaimReserveItemInfoTypeReserveDetails.


        :param reserve_detail: The reserve_detail of this ClaimReserveItemInfoTypeReserveDetails.
        :type reserve_detail: List[ReserveDetailType]
        """

        self._reserve_detail = reserve_detail
