# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.custom_field_type import CustomFieldType  # noqa: F401,E501
from swagger_server import util


class ClaimTypeCustomFields(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, custom_field: List[CustomFieldType]=None):  # noqa: E501
        """ClaimTypeCustomFields - a model defined in Swagger

        :param custom_field: The custom_field of this ClaimTypeCustomFields.  # noqa: E501
        :type custom_field: List[CustomFieldType]
        """
        self.swagger_types = {
            'custom_field': List[CustomFieldType]
        }

        self.attribute_map = {
            'custom_field': 'customField'
        }
        self._custom_field = custom_field

    @classmethod
    def from_dict(cls, dikt) -> 'ClaimTypeCustomFields':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClaimType_customFields of this ClaimTypeCustomFields.  # noqa: E501
        :rtype: ClaimTypeCustomFields
        """
        return util.deserialize_model(dikt, cls)

    @property
    def custom_field(self) -> List[CustomFieldType]:
        """Gets the custom_field of this ClaimTypeCustomFields.


        :return: The custom_field of this ClaimTypeCustomFields.
        :rtype: List[CustomFieldType]
        """
        return self._custom_field

    @custom_field.setter
    def custom_field(self, custom_field: List[CustomFieldType]):
        """Sets the custom_field of this ClaimTypeCustomFields.


        :param custom_field: The custom_field of this ClaimTypeCustomFields.
        :type custom_field: List[CustomFieldType]
        """

        self._custom_field = custom_field
