# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.claim_reserve_item_info_type import ClaimReserveItemInfoType  # noqa: F401,E501
from swagger_server import util


class ClaimTypeReserves(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, reserve: List[ClaimReserveItemInfoType]=None):  # noqa: E501
        """ClaimTypeReserves - a model defined in Swagger

        :param reserve: The reserve of this ClaimTypeReserves.  # noqa: E501
        :type reserve: List[ClaimReserveItemInfoType]
        """
        self.swagger_types = {
            'reserve': List[ClaimReserveItemInfoType]
        }

        self.attribute_map = {
            'reserve': 'reserve'
        }
        self._reserve = reserve

    @classmethod
    def from_dict(cls, dikt) -> 'ClaimTypeReserves':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClaimType_reserves of this ClaimTypeReserves.  # noqa: E501
        :rtype: ClaimTypeReserves
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reserve(self) -> List[ClaimReserveItemInfoType]:
        """Gets the reserve of this ClaimTypeReserves.


        :return: The reserve of this ClaimTypeReserves.
        :rtype: List[ClaimReserveItemInfoType]
        """
        return self._reserve

    @reserve.setter
    def reserve(self, reserve: List[ClaimReserveItemInfoType]):
        """Sets the reserve of this ClaimTypeReserves.


        :param reserve: The reserve of this ClaimTypeReserves.
        :type reserve: List[ClaimReserveItemInfoType]
        """

        self._reserve = reserve
