# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.amount_type import AmountType  # noqa: F401,E501
from swagger_server.models.claim_custom_type import ClaimCustomType  # noqa: F401,E501
from swagger_server.models.claim_type_custom_fields import ClaimTypeCustomFields  # noqa: F401,E501
from swagger_server.models.claim_type_history_modifications import ClaimTypeHistoryModifications  # noqa: F401,E501
from swagger_server.models.claim_type_incidents import ClaimTypeIncidents  # noqa: F401,E501
from swagger_server.models.claim_type_invoices import ClaimTypeInvoices  # noqa: F401,E501
from swagger_server.models.claim_type_notes import ClaimTypeNotes  # noqa: F401,E501
from swagger_server.models.claim_type_reserves import ClaimTypeReserves  # noqa: F401,E501
from swagger_server import util


class ClaimType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, member_nbr: int=None, member_external_reference_id: str=None, policy_nbr: int=None, policy_external_reference_id: str=None, occurence_date: datetime=None, type_id: str=None, external_reference_id: str=None, notification_method_id: str=None, notification_date: datetime=None, notification_time: datetime=None, notified_person_name: str=None, notifying_entity_id: str=None, notified_by: str=None, received_date: datetime=None, claim_nbr: int=None, status_id: str=None, insurance_company_nbr: int=None, package_nbr: int=None, creation_user_id: str=None, creation_date: datetime=None, total_reserve_amount: AmountType=None, custom: ClaimCustomType=None, custom_fields: ClaimTypeCustomFields=None, notes: ClaimTypeNotes=None, incidents: ClaimTypeIncidents=None, invoices: ClaimTypeInvoices=None, history_modifications: ClaimTypeHistoryModifications=None, reserves: ClaimTypeReserves=None):  # noqa: E501
        """ClaimType - a model defined in Swagger

        :param member_nbr: The member_nbr of this ClaimType.  # noqa: E501
        :type member_nbr: int
        :param member_external_reference_id: The member_external_reference_id of this ClaimType.  # noqa: E501
        :type member_external_reference_id: str
        :param policy_nbr: The policy_nbr of this ClaimType.  # noqa: E501
        :type policy_nbr: int
        :param policy_external_reference_id: The policy_external_reference_id of this ClaimType.  # noqa: E501
        :type policy_external_reference_id: str
        :param occurence_date: The occurence_date of this ClaimType.  # noqa: E501
        :type occurence_date: datetime
        :param type_id: The type_id of this ClaimType.  # noqa: E501
        :type type_id: str
        :param external_reference_id: The external_reference_id of this ClaimType.  # noqa: E501
        :type external_reference_id: str
        :param notification_method_id: The notification_method_id of this ClaimType.  # noqa: E501
        :type notification_method_id: str
        :param notification_date: The notification_date of this ClaimType.  # noqa: E501
        :type notification_date: datetime
        :param notification_time: The notification_time of this ClaimType.  # noqa: E501
        :type notification_time: datetime
        :param notified_person_name: The notified_person_name of this ClaimType.  # noqa: E501
        :type notified_person_name: str
        :param notifying_entity_id: The notifying_entity_id of this ClaimType.  # noqa: E501
        :type notifying_entity_id: str
        :param notified_by: The notified_by of this ClaimType.  # noqa: E501
        :type notified_by: str
        :param received_date: The received_date of this ClaimType.  # noqa: E501
        :type received_date: datetime
        :param claim_nbr: The claim_nbr of this ClaimType.  # noqa: E501
        :type claim_nbr: int
        :param status_id: The status_id of this ClaimType.  # noqa: E501
        :type status_id: str
        :param insurance_company_nbr: The insurance_company_nbr of this ClaimType.  # noqa: E501
        :type insurance_company_nbr: int
        :param package_nbr: The package_nbr of this ClaimType.  # noqa: E501
        :type package_nbr: int
        :param creation_user_id: The creation_user_id of this ClaimType.  # noqa: E501
        :type creation_user_id: str
        :param creation_date: The creation_date of this ClaimType.  # noqa: E501
        :type creation_date: datetime
        :param total_reserve_amount: The total_reserve_amount of this ClaimType.  # noqa: E501
        :type total_reserve_amount: AmountType
        :param custom: The custom of this ClaimType.  # noqa: E501
        :type custom: ClaimCustomType
        :param custom_fields: The custom_fields of this ClaimType.  # noqa: E501
        :type custom_fields: ClaimTypeCustomFields
        :param notes: The notes of this ClaimType.  # noqa: E501
        :type notes: ClaimTypeNotes
        :param incidents: The incidents of this ClaimType.  # noqa: E501
        :type incidents: ClaimTypeIncidents
        :param invoices: The invoices of this ClaimType.  # noqa: E501
        :type invoices: ClaimTypeInvoices
        :param history_modifications: The history_modifications of this ClaimType.  # noqa: E501
        :type history_modifications: ClaimTypeHistoryModifications
        :param reserves: The reserves of this ClaimType.  # noqa: E501
        :type reserves: ClaimTypeReserves
        """
        self.swagger_types = {
            'member_nbr': int,
            'member_external_reference_id': str,
            'policy_nbr': int,
            'policy_external_reference_id': str,
            'occurence_date': datetime,
            'type_id': str,
            'external_reference_id': str,
            'notification_method_id': str,
            'notification_date': datetime,
            'notification_time': datetime,
            'notified_person_name': str,
            'notifying_entity_id': str,
            'notified_by': str,
            'received_date': datetime,
            'claim_nbr': int,
            'status_id': str,
            'insurance_company_nbr': int,
            'package_nbr': int,
            'creation_user_id': str,
            'creation_date': datetime,
            'total_reserve_amount': AmountType,
            'custom': ClaimCustomType,
            'custom_fields': ClaimTypeCustomFields,
            'notes': ClaimTypeNotes,
            'incidents': ClaimTypeIncidents,
            'invoices': ClaimTypeInvoices,
            'history_modifications': ClaimTypeHistoryModifications,
            'reserves': ClaimTypeReserves
        }

        self.attribute_map = {
            'member_nbr': 'memberNbr',
            'member_external_reference_id': 'memberExternalReferenceId',
            'policy_nbr': 'policyNbr',
            'policy_external_reference_id': 'policyExternalReferenceId',
            'occurence_date': 'occurenceDate',
            'type_id': 'typeId',
            'external_reference_id': 'externalReferenceId',
            'notification_method_id': 'notificationMethodId',
            'notification_date': 'notificationDate',
            'notification_time': 'notificationTime',
            'notified_person_name': 'notifiedPersonName',
            'notifying_entity_id': 'notifyingEntityId',
            'notified_by': 'notifiedBy',
            'received_date': 'receivedDate',
            'claim_nbr': 'claimNbr',
            'status_id': 'statusId',
            'insurance_company_nbr': 'insuranceCompanyNbr',
            'package_nbr': 'packageNbr',
            'creation_user_id': 'creationUserId',
            'creation_date': 'creationDate',
            'total_reserve_amount': 'totalReserveAmount',
            'custom': 'custom',
            'custom_fields': 'customFields',
            'notes': 'notes',
            'incidents': 'incidents',
            'invoices': 'invoices',
            'history_modifications': 'historyModifications',
            'reserves': 'reserves'
        }
        self._member_nbr = member_nbr
        self._member_external_reference_id = member_external_reference_id
        self._policy_nbr = policy_nbr
        self._policy_external_reference_id = policy_external_reference_id
        self._occurence_date = occurence_date
        self._type_id = type_id
        self._external_reference_id = external_reference_id
        self._notification_method_id = notification_method_id
        self._notification_date = notification_date
        self._notification_time = notification_time
        self._notified_person_name = notified_person_name
        self._notifying_entity_id = notifying_entity_id
        self._notified_by = notified_by
        self._received_date = received_date
        self._claim_nbr = claim_nbr
        self._status_id = status_id
        self._insurance_company_nbr = insurance_company_nbr
        self._package_nbr = package_nbr
        self._creation_user_id = creation_user_id
        self._creation_date = creation_date
        self._total_reserve_amount = total_reserve_amount
        self._custom = custom
        self._custom_fields = custom_fields
        self._notes = notes
        self._incidents = incidents
        self._invoices = invoices
        self._history_modifications = history_modifications
        self._reserves = reserves

    @classmethod
    def from_dict(cls, dikt) -> 'ClaimType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClaimType of this ClaimType.  # noqa: E501
        :rtype: ClaimType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def member_nbr(self) -> int:
        """Gets the member_nbr of this ClaimType.


        :return: The member_nbr of this ClaimType.
        :rtype: int
        """
        return self._member_nbr

    @member_nbr.setter
    def member_nbr(self, member_nbr: int):
        """Sets the member_nbr of this ClaimType.


        :param member_nbr: The member_nbr of this ClaimType.
        :type member_nbr: int
        """

        self._member_nbr = member_nbr

    @property
    def member_external_reference_id(self) -> str:
        """Gets the member_external_reference_id of this ClaimType.


        :return: The member_external_reference_id of this ClaimType.
        :rtype: str
        """
        return self._member_external_reference_id

    @member_external_reference_id.setter
    def member_external_reference_id(self, member_external_reference_id: str):
        """Sets the member_external_reference_id of this ClaimType.


        :param member_external_reference_id: The member_external_reference_id of this ClaimType.
        :type member_external_reference_id: str
        """

        self._member_external_reference_id = member_external_reference_id

    @property
    def policy_nbr(self) -> int:
        """Gets the policy_nbr of this ClaimType.


        :return: The policy_nbr of this ClaimType.
        :rtype: int
        """
        return self._policy_nbr

    @policy_nbr.setter
    def policy_nbr(self, policy_nbr: int):
        """Sets the policy_nbr of this ClaimType.


        :param policy_nbr: The policy_nbr of this ClaimType.
        :type policy_nbr: int
        """

        self._policy_nbr = policy_nbr

    @property
    def policy_external_reference_id(self) -> str:
        """Gets the policy_external_reference_id of this ClaimType.


        :return: The policy_external_reference_id of this ClaimType.
        :rtype: str
        """
        return self._policy_external_reference_id

    @policy_external_reference_id.setter
    def policy_external_reference_id(self, policy_external_reference_id: str):
        """Sets the policy_external_reference_id of this ClaimType.


        :param policy_external_reference_id: The policy_external_reference_id of this ClaimType.
        :type policy_external_reference_id: str
        """

        self._policy_external_reference_id = policy_external_reference_id

    @property
    def occurence_date(self) -> datetime:
        """Gets the occurence_date of this ClaimType.


        :return: The occurence_date of this ClaimType.
        :rtype: datetime
        """
        return self._occurence_date

    @occurence_date.setter
    def occurence_date(self, occurence_date: datetime):
        """Sets the occurence_date of this ClaimType.


        :param occurence_date: The occurence_date of this ClaimType.
        :type occurence_date: datetime
        """

        self._occurence_date = occurence_date

    @property
    def type_id(self) -> str:
        """Gets the type_id of this ClaimType.


        :return: The type_id of this ClaimType.
        :rtype: str
        """
        return self._type_id

    @type_id.setter
    def type_id(self, type_id: str):
        """Sets the type_id of this ClaimType.


        :param type_id: The type_id of this ClaimType.
        :type type_id: str
        """

        self._type_id = type_id

    @property
    def external_reference_id(self) -> str:
        """Gets the external_reference_id of this ClaimType.


        :return: The external_reference_id of this ClaimType.
        :rtype: str
        """
        return self._external_reference_id

    @external_reference_id.setter
    def external_reference_id(self, external_reference_id: str):
        """Sets the external_reference_id of this ClaimType.


        :param external_reference_id: The external_reference_id of this ClaimType.
        :type external_reference_id: str
        """

        self._external_reference_id = external_reference_id

    @property
    def notification_method_id(self) -> str:
        """Gets the notification_method_id of this ClaimType.


        :return: The notification_method_id of this ClaimType.
        :rtype: str
        """
        return self._notification_method_id

    @notification_method_id.setter
    def notification_method_id(self, notification_method_id: str):
        """Sets the notification_method_id of this ClaimType.


        :param notification_method_id: The notification_method_id of this ClaimType.
        :type notification_method_id: str
        """

        self._notification_method_id = notification_method_id

    @property
    def notification_date(self) -> datetime:
        """Gets the notification_date of this ClaimType.


        :return: The notification_date of this ClaimType.
        :rtype: datetime
        """
        return self._notification_date

    @notification_date.setter
    def notification_date(self, notification_date: datetime):
        """Sets the notification_date of this ClaimType.


        :param notification_date: The notification_date of this ClaimType.
        :type notification_date: datetime
        """

        self._notification_date = notification_date

    @property
    def notification_time(self) -> datetime:
        """Gets the notification_time of this ClaimType.


        :return: The notification_time of this ClaimType.
        :rtype: datetime
        """
        return self._notification_time

    @notification_time.setter
    def notification_time(self, notification_time: datetime):
        """Sets the notification_time of this ClaimType.


        :param notification_time: The notification_time of this ClaimType.
        :type notification_time: datetime
        """

        self._notification_time = notification_time

    @property
    def notified_person_name(self) -> str:
        """Gets the notified_person_name of this ClaimType.


        :return: The notified_person_name of this ClaimType.
        :rtype: str
        """
        return self._notified_person_name

    @notified_person_name.setter
    def notified_person_name(self, notified_person_name: str):
        """Sets the notified_person_name of this ClaimType.


        :param notified_person_name: The notified_person_name of this ClaimType.
        :type notified_person_name: str
        """

        self._notified_person_name = notified_person_name

    @property
    def notifying_entity_id(self) -> str:
        """Gets the notifying_entity_id of this ClaimType.


        :return: The notifying_entity_id of this ClaimType.
        :rtype: str
        """
        return self._notifying_entity_id

    @notifying_entity_id.setter
    def notifying_entity_id(self, notifying_entity_id: str):
        """Sets the notifying_entity_id of this ClaimType.


        :param notifying_entity_id: The notifying_entity_id of this ClaimType.
        :type notifying_entity_id: str
        """

        self._notifying_entity_id = notifying_entity_id

    @property
    def notified_by(self) -> str:
        """Gets the notified_by of this ClaimType.


        :return: The notified_by of this ClaimType.
        :rtype: str
        """
        return self._notified_by

    @notified_by.setter
    def notified_by(self, notified_by: str):
        """Sets the notified_by of this ClaimType.


        :param notified_by: The notified_by of this ClaimType.
        :type notified_by: str
        """

        self._notified_by = notified_by

    @property
    def received_date(self) -> datetime:
        """Gets the received_date of this ClaimType.


        :return: The received_date of this ClaimType.
        :rtype: datetime
        """
        return self._received_date

    @received_date.setter
    def received_date(self, received_date: datetime):
        """Sets the received_date of this ClaimType.


        :param received_date: The received_date of this ClaimType.
        :type received_date: datetime
        """

        self._received_date = received_date

    @property
    def claim_nbr(self) -> int:
        """Gets the claim_nbr of this ClaimType.


        :return: The claim_nbr of this ClaimType.
        :rtype: int
        """
        return self._claim_nbr

    @claim_nbr.setter
    def claim_nbr(self, claim_nbr: int):
        """Sets the claim_nbr of this ClaimType.


        :param claim_nbr: The claim_nbr of this ClaimType.
        :type claim_nbr: int
        """

        self._claim_nbr = claim_nbr

    @property
    def status_id(self) -> str:
        """Gets the status_id of this ClaimType.


        :return: The status_id of this ClaimType.
        :rtype: str
        """
        return self._status_id

    @status_id.setter
    def status_id(self, status_id: str):
        """Sets the status_id of this ClaimType.


        :param status_id: The status_id of this ClaimType.
        :type status_id: str
        """

        self._status_id = status_id

    @property
    def insurance_company_nbr(self) -> int:
        """Gets the insurance_company_nbr of this ClaimType.


        :return: The insurance_company_nbr of this ClaimType.
        :rtype: int
        """
        return self._insurance_company_nbr

    @insurance_company_nbr.setter
    def insurance_company_nbr(self, insurance_company_nbr: int):
        """Sets the insurance_company_nbr of this ClaimType.


        :param insurance_company_nbr: The insurance_company_nbr of this ClaimType.
        :type insurance_company_nbr: int
        """

        self._insurance_company_nbr = insurance_company_nbr

    @property
    def package_nbr(self) -> int:
        """Gets the package_nbr of this ClaimType.


        :return: The package_nbr of this ClaimType.
        :rtype: int
        """
        return self._package_nbr

    @package_nbr.setter
    def package_nbr(self, package_nbr: int):
        """Sets the package_nbr of this ClaimType.


        :param package_nbr: The package_nbr of this ClaimType.
        :type package_nbr: int
        """

        self._package_nbr = package_nbr

    @property
    def creation_user_id(self) -> str:
        """Gets the creation_user_id of this ClaimType.


        :return: The creation_user_id of this ClaimType.
        :rtype: str
        """
        return self._creation_user_id

    @creation_user_id.setter
    def creation_user_id(self, creation_user_id: str):
        """Sets the creation_user_id of this ClaimType.


        :param creation_user_id: The creation_user_id of this ClaimType.
        :type creation_user_id: str
        """

        self._creation_user_id = creation_user_id

    @property
    def creation_date(self) -> datetime:
        """Gets the creation_date of this ClaimType.


        :return: The creation_date of this ClaimType.
        :rtype: datetime
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date: datetime):
        """Sets the creation_date of this ClaimType.


        :param creation_date: The creation_date of this ClaimType.
        :type creation_date: datetime
        """

        self._creation_date = creation_date

    @property
    def total_reserve_amount(self) -> AmountType:
        """Gets the total_reserve_amount of this ClaimType.


        :return: The total_reserve_amount of this ClaimType.
        :rtype: AmountType
        """
        return self._total_reserve_amount

    @total_reserve_amount.setter
    def total_reserve_amount(self, total_reserve_amount: AmountType):
        """Sets the total_reserve_amount of this ClaimType.


        :param total_reserve_amount: The total_reserve_amount of this ClaimType.
        :type total_reserve_amount: AmountType
        """

        self._total_reserve_amount = total_reserve_amount

    @property
    def custom(self) -> ClaimCustomType:
        """Gets the custom of this ClaimType.


        :return: The custom of this ClaimType.
        :rtype: ClaimCustomType
        """
        return self._custom

    @custom.setter
    def custom(self, custom: ClaimCustomType):
        """Sets the custom of this ClaimType.


        :param custom: The custom of this ClaimType.
        :type custom: ClaimCustomType
        """

        self._custom = custom

    @property
    def custom_fields(self) -> ClaimTypeCustomFields:
        """Gets the custom_fields of this ClaimType.


        :return: The custom_fields of this ClaimType.
        :rtype: ClaimTypeCustomFields
        """
        return self._custom_fields

    @custom_fields.setter
    def custom_fields(self, custom_fields: ClaimTypeCustomFields):
        """Sets the custom_fields of this ClaimType.


        :param custom_fields: The custom_fields of this ClaimType.
        :type custom_fields: ClaimTypeCustomFields
        """

        self._custom_fields = custom_fields

    @property
    def notes(self) -> ClaimTypeNotes:
        """Gets the notes of this ClaimType.


        :return: The notes of this ClaimType.
        :rtype: ClaimTypeNotes
        """
        return self._notes

    @notes.setter
    def notes(self, notes: ClaimTypeNotes):
        """Sets the notes of this ClaimType.


        :param notes: The notes of this ClaimType.
        :type notes: ClaimTypeNotes
        """

        self._notes = notes

    @property
    def incidents(self) -> ClaimTypeIncidents:
        """Gets the incidents of this ClaimType.


        :return: The incidents of this ClaimType.
        :rtype: ClaimTypeIncidents
        """
        return self._incidents

    @incidents.setter
    def incidents(self, incidents: ClaimTypeIncidents):
        """Sets the incidents of this ClaimType.


        :param incidents: The incidents of this ClaimType.
        :type incidents: ClaimTypeIncidents
        """

        self._incidents = incidents

    @property
    def invoices(self) -> ClaimTypeInvoices:
        """Gets the invoices of this ClaimType.


        :return: The invoices of this ClaimType.
        :rtype: ClaimTypeInvoices
        """
        return self._invoices

    @invoices.setter
    def invoices(self, invoices: ClaimTypeInvoices):
        """Sets the invoices of this ClaimType.


        :param invoices: The invoices of this ClaimType.
        :type invoices: ClaimTypeInvoices
        """

        self._invoices = invoices

    @property
    def history_modifications(self) -> ClaimTypeHistoryModifications:
        """Gets the history_modifications of this ClaimType.


        :return: The history_modifications of this ClaimType.
        :rtype: ClaimTypeHistoryModifications
        """
        return self._history_modifications

    @history_modifications.setter
    def history_modifications(self, history_modifications: ClaimTypeHistoryModifications):
        """Sets the history_modifications of this ClaimType.


        :param history_modifications: The history_modifications of this ClaimType.
        :type history_modifications: ClaimTypeHistoryModifications
        """

        self._history_modifications = history_modifications

    @property
    def reserves(self) -> ClaimTypeReserves:
        """Gets the reserves of this ClaimType.


        :return: The reserves of this ClaimType.
        :rtype: ClaimTypeReserves
        """
        return self._reserves

    @reserves.setter
    def reserves(self, reserves: ClaimTypeReserves):
        """Sets the reserves of this ClaimType.


        :param reserves: The reserves of this ClaimType.
        :type reserves: ClaimTypeReserves
        """

        self._reserves = reserves
