# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.claim_note_type import ClaimNoteType  # noqa: F401,E501
from swagger_server import util


class ClaimTypeNotes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, note: List[ClaimNoteType]=None):  # noqa: E501
        """ClaimTypeNotes - a model defined in Swagger

        :param note: The note of this ClaimTypeNotes.  # noqa: E501
        :type note: List[ClaimNoteType]
        """
        self.swagger_types = {
            'note': List[ClaimNoteType]
        }

        self.attribute_map = {
            'note': 'note'
        }
        self._note = note

    @classmethod
    def from_dict(cls, dikt) -> 'ClaimTypeNotes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClaimType_notes of this ClaimTypeNotes.  # noqa: E501
        :rtype: ClaimTypeNotes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def note(self) -> List[ClaimNoteType]:
        """Gets the note of this ClaimTypeNotes.


        :return: The note of this ClaimTypeNotes.
        :rtype: List[ClaimNoteType]
        """
        return self._note

    @note.setter
    def note(self, note: List[ClaimNoteType]):
        """Sets the note of this ClaimTypeNotes.


        :param note: The note of this ClaimTypeNotes.
        :type note: List[ClaimNoteType]
        """

        self._note = note
