# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.status_update_claim_item import StatusUpdateClaimItem  # noqa: F401,E501
from swagger_server import util


class CloseClaimCBMTypeClaims(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, claim: List[StatusUpdateClaimItem]=None):  # noqa: E501
        """CloseClaimCBMTypeClaims - a model defined in Swagger

        :param claim: The claim of this CloseClaimCBMTypeClaims.  # noqa: E501
        :type claim: List[StatusUpdateClaimItem]
        """
        self.swagger_types = {
            'claim': List[StatusUpdateClaimItem]
        }

        self.attribute_map = {
            'claim': 'claim'
        }
        self._claim = claim

    @classmethod
    def from_dict(cls, dikt) -> 'CloseClaimCBMTypeClaims':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CloseClaimCBMType_claims of this CloseClaimCBMTypeClaims.  # noqa: E501
        :rtype: CloseClaimCBMTypeClaims
        """
        return util.deserialize_model(dikt, cls)

    @property
    def claim(self) -> List[StatusUpdateClaimItem]:
        """Gets the claim of this CloseClaimCBMTypeClaims.


        :return: The claim of this CloseClaimCBMTypeClaims.
        :rtype: List[StatusUpdateClaimItem]
        """
        return self._claim

    @claim.setter
    def claim(self, claim: List[StatusUpdateClaimItem]):
        """Sets the claim of this CloseClaimCBMTypeClaims.


        :param claim: The claim of this CloseClaimCBMTypeClaims.
        :type claim: List[StatusUpdateClaimItem]
        """
        if claim is None:
            raise ValueError("Invalid value for `claim`, must not be `None`")  # noqa: E501

        self._claim = claim
