# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.invoice_type import InvoiceType  # noqa: F401,E501
from swagger_server import util


class CorrectInvoiceCBMType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, invoice: InvoiceType=None):  # noqa: E501
        """CorrectInvoiceCBMType - a model defined in Swagger

        :param invoice: The invoice of this CorrectInvoiceCBMType.  # noqa: E501
        :type invoice: InvoiceType
        """
        self.swagger_types = {
            'invoice': InvoiceType
        }

        self.attribute_map = {
            'invoice': 'invoice'
        }
        self._invoice = invoice

    @classmethod
    def from_dict(cls, dikt) -> 'CorrectInvoiceCBMType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CorrectInvoiceCBMType of this CorrectInvoiceCBMType.  # noqa: E501
        :rtype: CorrectInvoiceCBMType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def invoice(self) -> InvoiceType:
        """Gets the invoice of this CorrectInvoiceCBMType.


        :return: The invoice of this CorrectInvoiceCBMType.
        :rtype: InvoiceType
        """
        return self._invoice

    @invoice.setter
    def invoice(self, invoice: InvoiceType):
        """Sets the invoice of this CorrectInvoiceCBMType.


        :param invoice: The invoice of this CorrectInvoiceCBMType.
        :type invoice: InvoiceType
        """
        if invoice is None:
            raise ValueError("Invalid value for `invoice`, must not be `None`")  # noqa: E501

        self._invoice = invoice
