# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.create_claim_reserve_cbm_type_claims import CreateClaimReserveCBMTypeClaims  # noqa: F401,E501
from swagger_server import util


class CreateClaimReserveCBMType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, claims: CreateClaimReserveCBMTypeClaims=None):  # noqa: E501
        """CreateClaimReserveCBMType - a model defined in Swagger

        :param claims: The claims of this CreateClaimReserveCBMType.  # noqa: E501
        :type claims: CreateClaimReserveCBMTypeClaims
        """
        self.swagger_types = {
            'claims': CreateClaimReserveCBMTypeClaims
        }

        self.attribute_map = {
            'claims': 'claims'
        }
        self._claims = claims

    @classmethod
    def from_dict(cls, dikt) -> 'CreateClaimReserveCBMType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateClaimReserveCBMType of this CreateClaimReserveCBMType.  # noqa: E501
        :rtype: CreateClaimReserveCBMType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def claims(self) -> CreateClaimReserveCBMTypeClaims:
        """Gets the claims of this CreateClaimReserveCBMType.


        :return: The claims of this CreateClaimReserveCBMType.
        :rtype: CreateClaimReserveCBMTypeClaims
        """
        return self._claims

    @claims.setter
    def claims(self, claims: CreateClaimReserveCBMTypeClaims):
        """Sets the claims of this CreateClaimReserveCBMType.


        :param claims: The claims of this CreateClaimReserveCBMType.
        :type claims: CreateClaimReserveCBMTypeClaims
        """
        if claims is None:
            raise ValueError("Invalid value for `claims`, must not be `None`")  # noqa: E501

        self._claims = claims
