# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.create_claim_details_cbm_type_claims import CreateClaimDetailsCBMTypeClaims  # noqa: F401,E501
from swagger_server import util


class CreateClaimDetailsCBMType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, claims: CreateClaimDetailsCBMTypeClaims=None):  # noqa: E501
        """CreateClaimDetailsCBMType - a model defined in Swagger

        :param claims: The claims of this CreateClaimDetailsCBMType.  # noqa: E501
        :type claims: CreateClaimDetailsCBMTypeClaims
        """
        self.swagger_types = {
            'claims': CreateClaimDetailsCBMTypeClaims
        }

        self.attribute_map = {
            'claims': 'claims'
        }
        self._claims = claims

    @classmethod
    def from_dict(cls, dikt) -> 'CreateClaimDetailsCBMType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateClaimDetailsCBMType of this CreateClaimDetailsCBMType.  # noqa: E501
        :rtype: CreateClaimDetailsCBMType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def claims(self) -> CreateClaimDetailsCBMTypeClaims:
        """Gets the claims of this CreateClaimDetailsCBMType.


        :return: The claims of this CreateClaimDetailsCBMType.
        :rtype: CreateClaimDetailsCBMTypeClaims
        """
        return self._claims

    @claims.setter
    def claims(self, claims: CreateClaimDetailsCBMTypeClaims):
        """Sets the claims of this CreateClaimDetailsCBMType.


        :param claims: The claims of this CreateClaimDetailsCBMType.
        :type claims: CreateClaimDetailsCBMTypeClaims
        """
        if claims is None:
            raise ValueError("Invalid value for `claims`, must not be `None`")  # noqa: E501

        self._claims = claims
