# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.batch_type import BatchType  # noqa: F401,E501
from swagger_server import util


class CreateBatchCBMType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, batch: BatchType=None):  # noqa: E501
        """CreateBatchCBMType - a model defined in Swagger

        :param batch: The batch of this CreateBatchCBMType.  # noqa: E501
        :type batch: BatchType
        """
        self.swagger_types = {
            'batch': BatchType
        }

        self.attribute_map = {
            'batch': 'batch'
        }
        self._batch = batch

    @classmethod
    def from_dict(cls, dikt) -> 'CreateBatchCBMType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateBatchCBMType of this CreateBatchCBMType.  # noqa: E501
        :rtype: CreateBatchCBMType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def batch(self) -> BatchType:
        """Gets the batch of this CreateBatchCBMType.


        :return: The batch of this CreateBatchCBMType.
        :rtype: BatchType
        """
        return self._batch

    @batch.setter
    def batch(self, batch: BatchType):
        """Sets the batch of this CreateBatchCBMType.


        :param batch: The batch of this CreateBatchCBMType.
        :type batch: BatchType
        """
        if batch is None:
            raise ValueError("Invalid value for `batch`, must not be `None`")  # noqa: E501

        self._batch = batch
