# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.queue_item_type import QueueItemType  # noqa: F401,E501
from swagger_server import util


class CreateInvoiceImportResponseCBMType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, queue: QueueItemType=None):  # noqa: E501
        """CreateInvoiceImportResponseCBMType - a model defined in Swagger

        :param queue: The queue of this CreateInvoiceImportResponseCBMType.  # noqa: E501
        :type queue: QueueItemType
        """
        self.swagger_types = {
            'queue': QueueItemType
        }

        self.attribute_map = {
            'queue': 'queue'
        }
        self._queue = queue

    @classmethod
    def from_dict(cls, dikt) -> 'CreateInvoiceImportResponseCBMType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateInvoiceImportResponseCBMType of this CreateInvoiceImportResponseCBMType.  # noqa: E501
        :rtype: CreateInvoiceImportResponseCBMType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def queue(self) -> QueueItemType:
        """Gets the queue of this CreateInvoiceImportResponseCBMType.


        :return: The queue of this CreateInvoiceImportResponseCBMType.
        :rtype: QueueItemType
        """
        return self._queue

    @queue.setter
    def queue(self, queue: QueueItemType):
        """Sets the queue of this CreateInvoiceImportResponseCBMType.


        :param queue: The queue of this CreateInvoiceImportResponseCBMType.
        :type queue: QueueItemType
        """
        if queue is None:
            raise ValueError("Invalid value for `queue`, must not be `None`")  # noqa: E501

        self._queue = queue
