# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.create_claim_details_cbm_type_claims import CreateClaimDetailsCBMTypeClaims  # noqa: F401,E501
from swagger_server.models.queue_item_type import QueueItemType  # noqa: F401,E501
from swagger_server import util


class CreateClaimItemType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, queue_item: QueueItemType=None, claims: CreateClaimDetailsCBMTypeClaims=None):  # noqa: E501
        """CreateClaimItemType - a model defined in Swagger

        :param queue_item: The queue_item of this CreateClaimItemType.  # noqa: E501
        :type queue_item: QueueItemType
        :param claims: The claims of this CreateClaimItemType.  # noqa: E501
        :type claims: CreateClaimDetailsCBMTypeClaims
        """
        self.swagger_types = {
            'queue_item': QueueItemType,
            'claims': CreateClaimDetailsCBMTypeClaims
        }

        self.attribute_map = {
            'queue_item': 'queueItem',
            'claims': 'claims'
        }
        self._queue_item = queue_item
        self._claims = claims

    @classmethod
    def from_dict(cls, dikt) -> 'CreateClaimItemType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateClaimItemType of this CreateClaimItemType.  # noqa: E501
        :rtype: CreateClaimItemType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def queue_item(self) -> QueueItemType:
        """Gets the queue_item of this CreateClaimItemType.


        :return: The queue_item of this CreateClaimItemType.
        :rtype: QueueItemType
        """
        return self._queue_item

    @queue_item.setter
    def queue_item(self, queue_item: QueueItemType):
        """Sets the queue_item of this CreateClaimItemType.


        :param queue_item: The queue_item of this CreateClaimItemType.
        :type queue_item: QueueItemType
        """
        if queue_item is None:
            raise ValueError("Invalid value for `queue_item`, must not be `None`")  # noqa: E501

        self._queue_item = queue_item

    @property
    def claims(self) -> CreateClaimDetailsCBMTypeClaims:
        """Gets the claims of this CreateClaimItemType.


        :return: The claims of this CreateClaimItemType.
        :rtype: CreateClaimDetailsCBMTypeClaims
        """
        return self._claims

    @claims.setter
    def claims(self, claims: CreateClaimDetailsCBMTypeClaims):
        """Sets the claims of this CreateClaimItemType.


        :param claims: The claims of this CreateClaimItemType.
        :type claims: CreateClaimDetailsCBMTypeClaims
        """
        if claims is None:
            raise ValueError("Invalid value for `claims`, must not be `None`")  # noqa: E501

        self._claims = claims
