# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.error_type_error_message_parameterl_list_error_message_parameter import ErrorTypeErrorMessageParameterlListErrorMessageParameter  # noqa: F401,E501
from swagger_server import util


class ErrorTypeErrorMessageParameterlList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error_message_parameter: List[ErrorTypeErrorMessageParameterlListErrorMessageParameter]=None):  # noqa: E501
        """ErrorTypeErrorMessageParameterlList - a model defined in Swagger

        :param error_message_parameter: The error_message_parameter of this ErrorTypeErrorMessageParameterlList.  # noqa: E501
        :type error_message_parameter: List[ErrorTypeErrorMessageParameterlListErrorMessageParameter]
        """
        self.swagger_types = {
            'error_message_parameter': List[ErrorTypeErrorMessageParameterlListErrorMessageParameter]
        }

        self.attribute_map = {
            'error_message_parameter': 'errorMessageParameter'
        }
        self._error_message_parameter = error_message_parameter

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorTypeErrorMessageParameterlList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ErrorType_errorMessageParameterlList of this ErrorTypeErrorMessageParameterlList.  # noqa: E501
        :rtype: ErrorTypeErrorMessageParameterlList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_message_parameter(self) -> List[ErrorTypeErrorMessageParameterlListErrorMessageParameter]:
        """Gets the error_message_parameter of this ErrorTypeErrorMessageParameterlList.


        :return: The error_message_parameter of this ErrorTypeErrorMessageParameterlList.
        :rtype: List[ErrorTypeErrorMessageParameterlListErrorMessageParameter]
        """
        return self._error_message_parameter

    @error_message_parameter.setter
    def error_message_parameter(self, error_message_parameter: List[ErrorTypeErrorMessageParameterlListErrorMessageParameter]):
        """Sets the error_message_parameter of this ErrorTypeErrorMessageParameterlList.


        :param error_message_parameter: The error_message_parameter of this ErrorTypeErrorMessageParameterlList.
        :type error_message_parameter: List[ErrorTypeErrorMessageParameterlListErrorMessageParameter]
        """

        self._error_message_parameter = error_message_parameter
