# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ErrorInfoType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, timestamp: datetime=None, status: str=None, error: str=None, message: str=None, path: str=None):  # noqa: E501
        """ErrorInfoType - a model defined in Swagger

        :param timestamp: The timestamp of this ErrorInfoType.  # noqa: E501
        :type timestamp: datetime
        :param status: The status of this ErrorInfoType.  # noqa: E501
        :type status: str
        :param error: The error of this ErrorInfoType.  # noqa: E501
        :type error: str
        :param message: The message of this ErrorInfoType.  # noqa: E501
        :type message: str
        :param path: The path of this ErrorInfoType.  # noqa: E501
        :type path: str
        """
        self.swagger_types = {
            'timestamp': datetime,
            'status': str,
            'error': str,
            'message': str,
            'path': str
        }

        self.attribute_map = {
            'timestamp': 'timestamp',
            'status': 'status',
            'error': 'error',
            'message': 'message',
            'path': 'path'
        }
        self._timestamp = timestamp
        self._status = status
        self._error = error
        self._message = message
        self._path = path

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorInfoType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ErrorInfoType of this ErrorInfoType.  # noqa: E501
        :rtype: ErrorInfoType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this ErrorInfoType.


        :return: The timestamp of this ErrorInfoType.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this ErrorInfoType.


        :param timestamp: The timestamp of this ErrorInfoType.
        :type timestamp: datetime
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")  # noqa: E501

        self._timestamp = timestamp

    @property
    def status(self) -> str:
        """Gets the status of this ErrorInfoType.


        :return: The status of this ErrorInfoType.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this ErrorInfoType.


        :param status: The status of this ErrorInfoType.
        :type status: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def error(self) -> str:
        """Gets the error of this ErrorInfoType.


        :return: The error of this ErrorInfoType.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this ErrorInfoType.


        :param error: The error of this ErrorInfoType.
        :type error: str
        """
        if error is None:
            raise ValueError("Invalid value for `error`, must not be `None`")  # noqa: E501

        self._error = error

    @property
    def message(self) -> str:
        """Gets the message of this ErrorInfoType.


        :return: The message of this ErrorInfoType.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ErrorInfoType.


        :param message: The message of this ErrorInfoType.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def path(self) -> str:
        """Gets the path of this ErrorInfoType.


        :return: The path of this ErrorInfoType.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: str):
        """Sets the path of this ErrorInfoType.


        :param path: The path of this ErrorInfoType.
        :type path: str
        """
        if path is None:
            raise ValueError("Invalid value for `path`, must not be `None`")  # noqa: E501

        self._path = path
