# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class HospitalisationInfoType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, admission_date: date=None, admission_time: str=None, admission_type_id: str=None, admission_source_id: str=None, incident_class_id: str=None, discharge_date: date=None, discharge_time: str=None, estimated_length_of_stay: int=None):  # noqa: E501
        """HospitalisationInfoType - a model defined in Swagger

        :param admission_date: The admission_date of this HospitalisationInfoType.  # noqa: E501
        :type admission_date: date
        :param admission_time: The admission_time of this HospitalisationInfoType.  # noqa: E501
        :type admission_time: str
        :param admission_type_id: The admission_type_id of this HospitalisationInfoType.  # noqa: E501
        :type admission_type_id: str
        :param admission_source_id: The admission_source_id of this HospitalisationInfoType.  # noqa: E501
        :type admission_source_id: str
        :param incident_class_id: The incident_class_id of this HospitalisationInfoType.  # noqa: E501
        :type incident_class_id: str
        :param discharge_date: The discharge_date of this HospitalisationInfoType.  # noqa: E501
        :type discharge_date: date
        :param discharge_time: The discharge_time of this HospitalisationInfoType.  # noqa: E501
        :type discharge_time: str
        :param estimated_length_of_stay: The estimated_length_of_stay of this HospitalisationInfoType.  # noqa: E501
        :type estimated_length_of_stay: int
        """
        self.swagger_types = {
            'admission_date': date,
            'admission_time': str,
            'admission_type_id': str,
            'admission_source_id': str,
            'incident_class_id': str,
            'discharge_date': date,
            'discharge_time': str,
            'estimated_length_of_stay': int
        }

        self.attribute_map = {
            'admission_date': 'admissionDate',
            'admission_time': 'admissionTime',
            'admission_type_id': 'admissionTypeId',
            'admission_source_id': 'admissionSourceId',
            'incident_class_id': 'incidentClassId',
            'discharge_date': 'dischargeDate',
            'discharge_time': 'dischargeTime',
            'estimated_length_of_stay': 'estimatedLengthOfStay'
        }
        self._admission_date = admission_date
        self._admission_time = admission_time
        self._admission_type_id = admission_type_id
        self._admission_source_id = admission_source_id
        self._incident_class_id = incident_class_id
        self._discharge_date = discharge_date
        self._discharge_time = discharge_time
        self._estimated_length_of_stay = estimated_length_of_stay

    @classmethod
    def from_dict(cls, dikt) -> 'HospitalisationInfoType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HospitalisationInfoType of this HospitalisationInfoType.  # noqa: E501
        :rtype: HospitalisationInfoType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def admission_date(self) -> date:
        """Gets the admission_date of this HospitalisationInfoType.


        :return: The admission_date of this HospitalisationInfoType.
        :rtype: date
        """
        return self._admission_date

    @admission_date.setter
    def admission_date(self, admission_date: date):
        """Sets the admission_date of this HospitalisationInfoType.


        :param admission_date: The admission_date of this HospitalisationInfoType.
        :type admission_date: date
        """

        self._admission_date = admission_date

    @property
    def admission_time(self) -> str:
        """Gets the admission_time of this HospitalisationInfoType.


        :return: The admission_time of this HospitalisationInfoType.
        :rtype: str
        """
        return self._admission_time

    @admission_time.setter
    def admission_time(self, admission_time: str):
        """Sets the admission_time of this HospitalisationInfoType.


        :param admission_time: The admission_time of this HospitalisationInfoType.
        :type admission_time: str
        """

        self._admission_time = admission_time

    @property
    def admission_type_id(self) -> str:
        """Gets the admission_type_id of this HospitalisationInfoType.


        :return: The admission_type_id of this HospitalisationInfoType.
        :rtype: str
        """
        return self._admission_type_id

    @admission_type_id.setter
    def admission_type_id(self, admission_type_id: str):
        """Sets the admission_type_id of this HospitalisationInfoType.


        :param admission_type_id: The admission_type_id of this HospitalisationInfoType.
        :type admission_type_id: str
        """

        self._admission_type_id = admission_type_id

    @property
    def admission_source_id(self) -> str:
        """Gets the admission_source_id of this HospitalisationInfoType.


        :return: The admission_source_id of this HospitalisationInfoType.
        :rtype: str
        """
        return self._admission_source_id

    @admission_source_id.setter
    def admission_source_id(self, admission_source_id: str):
        """Sets the admission_source_id of this HospitalisationInfoType.


        :param admission_source_id: The admission_source_id of this HospitalisationInfoType.
        :type admission_source_id: str
        """

        self._admission_source_id = admission_source_id

    @property
    def incident_class_id(self) -> str:
        """Gets the incident_class_id of this HospitalisationInfoType.


        :return: The incident_class_id of this HospitalisationInfoType.
        :rtype: str
        """
        return self._incident_class_id

    @incident_class_id.setter
    def incident_class_id(self, incident_class_id: str):
        """Sets the incident_class_id of this HospitalisationInfoType.


        :param incident_class_id: The incident_class_id of this HospitalisationInfoType.
        :type incident_class_id: str
        """

        self._incident_class_id = incident_class_id

    @property
    def discharge_date(self) -> date:
        """Gets the discharge_date of this HospitalisationInfoType.


        :return: The discharge_date of this HospitalisationInfoType.
        :rtype: date
        """
        return self._discharge_date

    @discharge_date.setter
    def discharge_date(self, discharge_date: date):
        """Sets the discharge_date of this HospitalisationInfoType.


        :param discharge_date: The discharge_date of this HospitalisationInfoType.
        :type discharge_date: date
        """

        self._discharge_date = discharge_date

    @property
    def discharge_time(self) -> str:
        """Gets the discharge_time of this HospitalisationInfoType.


        :return: The discharge_time of this HospitalisationInfoType.
        :rtype: str
        """
        return self._discharge_time

    @discharge_time.setter
    def discharge_time(self, discharge_time: str):
        """Sets the discharge_time of this HospitalisationInfoType.


        :param discharge_time: The discharge_time of this HospitalisationInfoType.
        :type discharge_time: str
        """

        self._discharge_time = discharge_time

    @property
    def estimated_length_of_stay(self) -> int:
        """Gets the estimated_length_of_stay of this HospitalisationInfoType.


        :return: The estimated_length_of_stay of this HospitalisationInfoType.
        :rtype: int
        """
        return self._estimated_length_of_stay

    @estimated_length_of_stay.setter
    def estimated_length_of_stay(self, estimated_length_of_stay: int):
        """Sets the estimated_length_of_stay of this HospitalisationInfoType.


        :param estimated_length_of_stay: The estimated_length_of_stay of this HospitalisationInfoType.
        :type estimated_length_of_stay: int
        """

        self._estimated_length_of_stay = estimated_length_of_stay
