# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.hospitalisation_info_type import HospitalisationInfoType  # noqa: F401,E501
from swagger_server.models.outpatient_info_type import OutpatientInfoType  # noqa: F401,E501
from swagger_server import util


class IncidentTypeInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, hospitalisation_info: HospitalisationInfoType=None, outpatient_info: OutpatientInfoType=None):  # noqa: E501
        """IncidentTypeInfo - a model defined in Swagger

        :param hospitalisation_info: The hospitalisation_info of this IncidentTypeInfo.  # noqa: E501
        :type hospitalisation_info: HospitalisationInfoType
        :param outpatient_info: The outpatient_info of this IncidentTypeInfo.  # noqa: E501
        :type outpatient_info: OutpatientInfoType
        """
        self.swagger_types = {
            'hospitalisation_info': HospitalisationInfoType,
            'outpatient_info': OutpatientInfoType
        }

        self.attribute_map = {
            'hospitalisation_info': 'hospitalisationInfo',
            'outpatient_info': 'outpatientInfo'
        }
        self._hospitalisation_info = hospitalisation_info
        self._outpatient_info = outpatient_info

    @classmethod
    def from_dict(cls, dikt) -> 'IncidentTypeInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IncidentTypeInfo of this IncidentTypeInfo.  # noqa: E501
        :rtype: IncidentTypeInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def hospitalisation_info(self) -> HospitalisationInfoType:
        """Gets the hospitalisation_info of this IncidentTypeInfo.


        :return: The hospitalisation_info of this IncidentTypeInfo.
        :rtype: HospitalisationInfoType
        """
        return self._hospitalisation_info

    @hospitalisation_info.setter
    def hospitalisation_info(self, hospitalisation_info: HospitalisationInfoType):
        """Sets the hospitalisation_info of this IncidentTypeInfo.


        :param hospitalisation_info: The hospitalisation_info of this IncidentTypeInfo.
        :type hospitalisation_info: HospitalisationInfoType
        """

        self._hospitalisation_info = hospitalisation_info

    @property
    def outpatient_info(self) -> OutpatientInfoType:
        """Gets the outpatient_info of this IncidentTypeInfo.


        :return: The outpatient_info of this IncidentTypeInfo.
        :rtype: OutpatientInfoType
        """
        return self._outpatient_info

    @outpatient_info.setter
    def outpatient_info(self, outpatient_info: OutpatientInfoType):
        """Sets the outpatient_info of this IncidentTypeInfo.


        :param outpatient_info: The outpatient_info of this IncidentTypeInfo.
        :type outpatient_info: OutpatientInfoType
        """

        self._outpatient_info = outpatient_info
