# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response202_queue_item_sub_item_list import InlineResponse202QueueItemSubItemList  # noqa: F401,E501
from swagger_server import util


class InlineResponse202QueueItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, queue_nbr: int=None, external_reference: str=None, queue_parent_nbr: int=None, queue_item_nbr: int=None, resource_path: str=None, resource_id: str=None, creation_date: str=None, modification_date: str=None, error_code: str=None, error_message: str=None, status: str=None, sub_item_list: InlineResponse202QueueItemSubItemList=None):  # noqa: E501
        """InlineResponse202QueueItem - a model defined in Swagger

        :param queue_nbr: The queue_nbr of this InlineResponse202QueueItem.  # noqa: E501
        :type queue_nbr: int
        :param external_reference: The external_reference of this InlineResponse202QueueItem.  # noqa: E501
        :type external_reference: str
        :param queue_parent_nbr: The queue_parent_nbr of this InlineResponse202QueueItem.  # noqa: E501
        :type queue_parent_nbr: int
        :param queue_item_nbr: The queue_item_nbr of this InlineResponse202QueueItem.  # noqa: E501
        :type queue_item_nbr: int
        :param resource_path: The resource_path of this InlineResponse202QueueItem.  # noqa: E501
        :type resource_path: str
        :param resource_id: The resource_id of this InlineResponse202QueueItem.  # noqa: E501
        :type resource_id: str
        :param creation_date: The creation_date of this InlineResponse202QueueItem.  # noqa: E501
        :type creation_date: str
        :param modification_date: The modification_date of this InlineResponse202QueueItem.  # noqa: E501
        :type modification_date: str
        :param error_code: The error_code of this InlineResponse202QueueItem.  # noqa: E501
        :type error_code: str
        :param error_message: The error_message of this InlineResponse202QueueItem.  # noqa: E501
        :type error_message: str
        :param status: The status of this InlineResponse202QueueItem.  # noqa: E501
        :type status: str
        :param sub_item_list: The sub_item_list of this InlineResponse202QueueItem.  # noqa: E501
        :type sub_item_list: InlineResponse202QueueItemSubItemList
        """
        self.swagger_types = {
            'queue_nbr': int,
            'external_reference': str,
            'queue_parent_nbr': int,
            'queue_item_nbr': int,
            'resource_path': str,
            'resource_id': str,
            'creation_date': str,
            'modification_date': str,
            'error_code': str,
            'error_message': str,
            'status': str,
            'sub_item_list': InlineResponse202QueueItemSubItemList
        }

        self.attribute_map = {
            'queue_nbr': 'queueNbr',
            'external_reference': 'externalReference',
            'queue_parent_nbr': 'queueParentNbr',
            'queue_item_nbr': 'queueItemNbr',
            'resource_path': 'resourcePath',
            'resource_id': 'resourceId',
            'creation_date': 'creationDate',
            'modification_date': 'modificationDate',
            'error_code': 'errorCode',
            'error_message': 'errorMessage',
            'status': 'status',
            'sub_item_list': 'subItemList'
        }
        self._queue_nbr = queue_nbr
        self._external_reference = external_reference
        self._queue_parent_nbr = queue_parent_nbr
        self._queue_item_nbr = queue_item_nbr
        self._resource_path = resource_path
        self._resource_id = resource_id
        self._creation_date = creation_date
        self._modification_date = modification_date
        self._error_code = error_code
        self._error_message = error_message
        self._status = status
        self._sub_item_list = sub_item_list

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse202QueueItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_202_queueItem of this InlineResponse202QueueItem.  # noqa: E501
        :rtype: InlineResponse202QueueItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def queue_nbr(self) -> int:
        """Gets the queue_nbr of this InlineResponse202QueueItem.


        :return: The queue_nbr of this InlineResponse202QueueItem.
        :rtype: int
        """
        return self._queue_nbr

    @queue_nbr.setter
    def queue_nbr(self, queue_nbr: int):
        """Sets the queue_nbr of this InlineResponse202QueueItem.


        :param queue_nbr: The queue_nbr of this InlineResponse202QueueItem.
        :type queue_nbr: int
        """

        self._queue_nbr = queue_nbr

    @property
    def external_reference(self) -> str:
        """Gets the external_reference of this InlineResponse202QueueItem.


        :return: The external_reference of this InlineResponse202QueueItem.
        :rtype: str
        """
        return self._external_reference

    @external_reference.setter
    def external_reference(self, external_reference: str):
        """Sets the external_reference of this InlineResponse202QueueItem.


        :param external_reference: The external_reference of this InlineResponse202QueueItem.
        :type external_reference: str
        """

        self._external_reference = external_reference

    @property
    def queue_parent_nbr(self) -> int:
        """Gets the queue_parent_nbr of this InlineResponse202QueueItem.


        :return: The queue_parent_nbr of this InlineResponse202QueueItem.
        :rtype: int
        """
        return self._queue_parent_nbr

    @queue_parent_nbr.setter
    def queue_parent_nbr(self, queue_parent_nbr: int):
        """Sets the queue_parent_nbr of this InlineResponse202QueueItem.


        :param queue_parent_nbr: The queue_parent_nbr of this InlineResponse202QueueItem.
        :type queue_parent_nbr: int
        """

        self._queue_parent_nbr = queue_parent_nbr

    @property
    def queue_item_nbr(self) -> int:
        """Gets the queue_item_nbr of this InlineResponse202QueueItem.


        :return: The queue_item_nbr of this InlineResponse202QueueItem.
        :rtype: int
        """
        return self._queue_item_nbr

    @queue_item_nbr.setter
    def queue_item_nbr(self, queue_item_nbr: int):
        """Sets the queue_item_nbr of this InlineResponse202QueueItem.


        :param queue_item_nbr: The queue_item_nbr of this InlineResponse202QueueItem.
        :type queue_item_nbr: int
        """

        self._queue_item_nbr = queue_item_nbr

    @property
    def resource_path(self) -> str:
        """Gets the resource_path of this InlineResponse202QueueItem.


        :return: The resource_path of this InlineResponse202QueueItem.
        :rtype: str
        """
        return self._resource_path

    @resource_path.setter
    def resource_path(self, resource_path: str):
        """Sets the resource_path of this InlineResponse202QueueItem.


        :param resource_path: The resource_path of this InlineResponse202QueueItem.
        :type resource_path: str
        """

        self._resource_path = resource_path

    @property
    def resource_id(self) -> str:
        """Gets the resource_id of this InlineResponse202QueueItem.


        :return: The resource_id of this InlineResponse202QueueItem.
        :rtype: str
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id: str):
        """Sets the resource_id of this InlineResponse202QueueItem.


        :param resource_id: The resource_id of this InlineResponse202QueueItem.
        :type resource_id: str
        """

        self._resource_id = resource_id

    @property
    def creation_date(self) -> str:
        """Gets the creation_date of this InlineResponse202QueueItem.


        :return: The creation_date of this InlineResponse202QueueItem.
        :rtype: str
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date: str):
        """Sets the creation_date of this InlineResponse202QueueItem.


        :param creation_date: The creation_date of this InlineResponse202QueueItem.
        :type creation_date: str
        """

        self._creation_date = creation_date

    @property
    def modification_date(self) -> str:
        """Gets the modification_date of this InlineResponse202QueueItem.


        :return: The modification_date of this InlineResponse202QueueItem.
        :rtype: str
        """
        return self._modification_date

    @modification_date.setter
    def modification_date(self, modification_date: str):
        """Sets the modification_date of this InlineResponse202QueueItem.


        :param modification_date: The modification_date of this InlineResponse202QueueItem.
        :type modification_date: str
        """

        self._modification_date = modification_date

    @property
    def error_code(self) -> str:
        """Gets the error_code of this InlineResponse202QueueItem.


        :return: The error_code of this InlineResponse202QueueItem.
        :rtype: str
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code: str):
        """Sets the error_code of this InlineResponse202QueueItem.


        :param error_code: The error_code of this InlineResponse202QueueItem.
        :type error_code: str
        """

        self._error_code = error_code

    @property
    def error_message(self) -> str:
        """Gets the error_message of this InlineResponse202QueueItem.


        :return: The error_message of this InlineResponse202QueueItem.
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message: str):
        """Sets the error_message of this InlineResponse202QueueItem.


        :param error_message: The error_message of this InlineResponse202QueueItem.
        :type error_message: str
        """

        self._error_message = error_message

    @property
    def status(self) -> str:
        """Gets the status of this InlineResponse202QueueItem.


        :return: The status of this InlineResponse202QueueItem.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this InlineResponse202QueueItem.


        :param status: The status of this InlineResponse202QueueItem.
        :type status: str
        """

        self._status = status

    @property
    def sub_item_list(self) -> InlineResponse202QueueItemSubItemList:
        """Gets the sub_item_list of this InlineResponse202QueueItem.


        :return: The sub_item_list of this InlineResponse202QueueItem.
        :rtype: InlineResponse202QueueItemSubItemList
        """
        return self._sub_item_list

    @sub_item_list.setter
    def sub_item_list(self, sub_item_list: InlineResponse202QueueItemSubItemList):
        """Sets the sub_item_list of this InlineResponse202QueueItem.


        :param sub_item_list: The sub_item_list of this InlineResponse202QueueItem.
        :type sub_item_list: InlineResponse202QueueItemSubItemList
        """

        self._sub_item_list = sub_item_list
