# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response202_queue_item import InlineResponse202QueueItem  # noqa: F401,E501
from swagger_server import util


class InlineResponse202(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, queue_item: InlineResponse202QueueItem=None):  # noqa: E501
        """InlineResponse202 - a model defined in Swagger

        :param queue_item: The queue_item of this InlineResponse202.  # noqa: E501
        :type queue_item: InlineResponse202QueueItem
        """
        self.swagger_types = {
            'queue_item': InlineResponse202QueueItem
        }

        self.attribute_map = {
            'queue_item': 'queueItem'
        }
        self._queue_item = queue_item

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse202':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_202 of this InlineResponse202.  # noqa: E501
        :rtype: InlineResponse202
        """
        return util.deserialize_model(dikt, cls)

    @property
    def queue_item(self) -> InlineResponse202QueueItem:
        """Gets the queue_item of this InlineResponse202.


        :return: The queue_item of this InlineResponse202.
        :rtype: InlineResponse202QueueItem
        """
        return self._queue_item

    @queue_item.setter
    def queue_item(self, queue_item: InlineResponse202QueueItem):
        """Sets the queue_item of this InlineResponse202.


        :param queue_item: The queue_item of this InlineResponse202.
        :type queue_item: InlineResponse202QueueItem
        """

        self._queue_item = queue_item
