# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response202_queue_item_sub_item_list_sub_item import InlineResponse202QueueItemSubItemListSubItem  # noqa: F401,E501
from swagger_server import util


class InlineResponse202QueueItemSubItemList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, sub_item: List[InlineResponse202QueueItemSubItemListSubItem]=None):  # noqa: E501
        """InlineResponse202QueueItemSubItemList - a model defined in Swagger

        :param sub_item: The sub_item of this InlineResponse202QueueItemSubItemList.  # noqa: E501
        :type sub_item: List[InlineResponse202QueueItemSubItemListSubItem]
        """
        self.swagger_types = {
            'sub_item': List[InlineResponse202QueueItemSubItemListSubItem]
        }

        self.attribute_map = {
            'sub_item': 'subItem'
        }
        self._sub_item = sub_item

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse202QueueItemSubItemList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_202_queueItem_subItemList of this InlineResponse202QueueItemSubItemList.  # noqa: E501
        :rtype: InlineResponse202QueueItemSubItemList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sub_item(self) -> List[InlineResponse202QueueItemSubItemListSubItem]:
        """Gets the sub_item of this InlineResponse202QueueItemSubItemList.


        :return: The sub_item of this InlineResponse202QueueItemSubItemList.
        :rtype: List[InlineResponse202QueueItemSubItemListSubItem]
        """
        return self._sub_item

    @sub_item.setter
    def sub_item(self, sub_item: List[InlineResponse202QueueItemSubItemListSubItem]):
        """Sets the sub_item of this InlineResponse202QueueItemSubItemList.


        :param sub_item: The sub_item of this InlineResponse202QueueItemSubItemList.
        :type sub_item: List[InlineResponse202QueueItemSubItemListSubItem]
        """

        self._sub_item = sub_item
