# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse202QueueItemSubItemListSubItemListSubItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, creation_date: str=None):  # noqa: E501
        """InlineResponse202QueueItemSubItemListSubItemListSubItem - a model defined in Swagger

        :param creation_date: The creation_date of this InlineResponse202QueueItemSubItemListSubItemListSubItem.  # noqa: E501
        :type creation_date: str
        """
        self.swagger_types = {
            'creation_date': str
        }

        self.attribute_map = {
            'creation_date': 'creationDate'
        }
        self._creation_date = creation_date

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse202QueueItemSubItemListSubItemListSubItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_202_queueItem_subItemList_subItemList_subItem of this InlineResponse202QueueItemSubItemListSubItemListSubItem.  # noqa: E501
        :rtype: InlineResponse202QueueItemSubItemListSubItemListSubItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def creation_date(self) -> str:
        """Gets the creation_date of this InlineResponse202QueueItemSubItemListSubItemListSubItem.


        :return: The creation_date of this InlineResponse202QueueItemSubItemListSubItemListSubItem.
        :rtype: str
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date: str):
        """Sets the creation_date of this InlineResponse202QueueItemSubItemListSubItemListSubItem.


        :param creation_date: The creation_date of this InlineResponse202QueueItemSubItemListSubItemListSubItem.
        :type creation_date: str
        """

        self._creation_date = creation_date
