# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.invoice_import_note_type import InvoiceImportNoteType  # noqa: F401,E501
from swagger_server import util


class InvoiceImportRequestType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, provider_id: str=None, insurance_company_nbr: int=None, received_date: datetime=None, note: InvoiceImportNoteType=None, file: str=None):  # noqa: E501
        """InvoiceImportRequestType - a model defined in Swagger

        :param provider_id: The provider_id of this InvoiceImportRequestType.  # noqa: E501
        :type provider_id: str
        :param insurance_company_nbr: The insurance_company_nbr of this InvoiceImportRequestType.  # noqa: E501
        :type insurance_company_nbr: int
        :param received_date: The received_date of this InvoiceImportRequestType.  # noqa: E501
        :type received_date: datetime
        :param note: The note of this InvoiceImportRequestType.  # noqa: E501
        :type note: InvoiceImportNoteType
        :param file: The file of this InvoiceImportRequestType.  # noqa: E501
        :type file: str
        """
        self.swagger_types = {
            'provider_id': str,
            'insurance_company_nbr': int,
            'received_date': datetime,
            'note': InvoiceImportNoteType,
            'file': str
        }

        self.attribute_map = {
            'provider_id': 'providerId',
            'insurance_company_nbr': 'insuranceCompanyNbr',
            'received_date': 'receivedDate',
            'note': 'note',
            'file': 'file'
        }
        self._provider_id = provider_id
        self._insurance_company_nbr = insurance_company_nbr
        self._received_date = received_date
        self._note = note
        self._file = file

    @classmethod
    def from_dict(cls, dikt) -> 'InvoiceImportRequestType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InvoiceImportRequestType of this InvoiceImportRequestType.  # noqa: E501
        :rtype: InvoiceImportRequestType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def provider_id(self) -> str:
        """Gets the provider_id of this InvoiceImportRequestType.


        :return: The provider_id of this InvoiceImportRequestType.
        :rtype: str
        """
        return self._provider_id

    @provider_id.setter
    def provider_id(self, provider_id: str):
        """Sets the provider_id of this InvoiceImportRequestType.


        :param provider_id: The provider_id of this InvoiceImportRequestType.
        :type provider_id: str
        """

        self._provider_id = provider_id

    @property
    def insurance_company_nbr(self) -> int:
        """Gets the insurance_company_nbr of this InvoiceImportRequestType.


        :return: The insurance_company_nbr of this InvoiceImportRequestType.
        :rtype: int
        """
        return self._insurance_company_nbr

    @insurance_company_nbr.setter
    def insurance_company_nbr(self, insurance_company_nbr: int):
        """Sets the insurance_company_nbr of this InvoiceImportRequestType.


        :param insurance_company_nbr: The insurance_company_nbr of this InvoiceImportRequestType.
        :type insurance_company_nbr: int
        """

        self._insurance_company_nbr = insurance_company_nbr

    @property
    def received_date(self) -> datetime:
        """Gets the received_date of this InvoiceImportRequestType.


        :return: The received_date of this InvoiceImportRequestType.
        :rtype: datetime
        """
        return self._received_date

    @received_date.setter
    def received_date(self, received_date: datetime):
        """Sets the received_date of this InvoiceImportRequestType.


        :param received_date: The received_date of this InvoiceImportRequestType.
        :type received_date: datetime
        """

        self._received_date = received_date

    @property
    def note(self) -> InvoiceImportNoteType:
        """Gets the note of this InvoiceImportRequestType.


        :return: The note of this InvoiceImportRequestType.
        :rtype: InvoiceImportNoteType
        """
        return self._note

    @note.setter
    def note(self, note: InvoiceImportNoteType):
        """Sets the note of this InvoiceImportRequestType.


        :param note: The note of this InvoiceImportRequestType.
        :type note: InvoiceImportNoteType
        """

        self._note = note

    @property
    def file(self) -> str:
        """Gets the file of this InvoiceImportRequestType.


        :return: The file of this InvoiceImportRequestType.
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file: str):
        """Sets the file of this InvoiceImportRequestType.


        :param file: The file of this InvoiceImportRequestType.
        :type file: str
        """
        if file is None:
            raise ValueError("Invalid value for `file`, must not be `None`")  # noqa: E501

        self._file = file
