# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.note_type import NoteType  # noqa: F401,E501
from swagger_server import util


class InvoiceTypeNotes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, note: List[NoteType]=None):  # noqa: E501
        """InvoiceTypeNotes - a model defined in Swagger

        :param note: The note of this InvoiceTypeNotes.  # noqa: E501
        :type note: List[NoteType]
        """
        self.swagger_types = {
            'note': List[NoteType]
        }

        self.attribute_map = {
            'note': 'note'
        }
        self._note = note

    @classmethod
    def from_dict(cls, dikt) -> 'InvoiceTypeNotes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InvoiceType_notes of this InvoiceTypeNotes.  # noqa: E501
        :rtype: InvoiceTypeNotes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def note(self) -> List[NoteType]:
        """Gets the note of this InvoiceTypeNotes.


        :return: The note of this InvoiceTypeNotes.
        :rtype: List[NoteType]
        """
        return self._note

    @note.setter
    def note(self, note: List[NoteType]):
        """Sets the note of this InvoiceTypeNotes.


        :param note: The note of this InvoiceTypeNotes.
        :type note: List[NoteType]
        """

        self._note = note
