# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.invoice_import_type import InvoiceImportType  # noqa: F401,E501
from swagger_server import util


class InvoiceImportsType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, invoice_import: List[InvoiceImportType]=None):  # noqa: E501
        """InvoiceImportsType - a model defined in Swagger

        :param invoice_import: The invoice_import of this InvoiceImportsType.  # noqa: E501
        :type invoice_import: List[InvoiceImportType]
        """
        self.swagger_types = {
            'invoice_import': List[InvoiceImportType]
        }

        self.attribute_map = {
            'invoice_import': 'invoiceImport'
        }
        self._invoice_import = invoice_import

    @classmethod
    def from_dict(cls, dikt) -> 'InvoiceImportsType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InvoiceImportsType of this InvoiceImportsType.  # noqa: E501
        :rtype: InvoiceImportsType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def invoice_import(self) -> List[InvoiceImportType]:
        """Gets the invoice_import of this InvoiceImportsType.


        :return: The invoice_import of this InvoiceImportsType.
        :rtype: List[InvoiceImportType]
        """
        return self._invoice_import

    @invoice_import.setter
    def invoice_import(self, invoice_import: List[InvoiceImportType]):
        """Sets the invoice_import of this InvoiceImportsType.


        :param invoice_import: The invoice_import of this InvoiceImportsType.
        :type invoice_import: List[InvoiceImportType]
        """

        self._invoice_import = invoice_import
