# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.invoice_import_transaction_type import InvoiceImportTransactionType  # noqa: F401,E501
from swagger_server import util


class InvoiceImportTypeInvoiceImportTransactions(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, invoice_import_transaction: List[InvoiceImportTransactionType]=None):  # noqa: E501
        """InvoiceImportTypeInvoiceImportTransactions - a model defined in Swagger

        :param invoice_import_transaction: The invoice_import_transaction of this InvoiceImportTypeInvoiceImportTransactions.  # noqa: E501
        :type invoice_import_transaction: List[InvoiceImportTransactionType]
        """
        self.swagger_types = {
            'invoice_import_transaction': List[InvoiceImportTransactionType]
        }

        self.attribute_map = {
            'invoice_import_transaction': 'invoiceImportTransaction'
        }
        self._invoice_import_transaction = invoice_import_transaction

    @classmethod
    def from_dict(cls, dikt) -> 'InvoiceImportTypeInvoiceImportTransactions':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InvoiceImportType_invoiceImportTransactions of this InvoiceImportTypeInvoiceImportTransactions.  # noqa: E501
        :rtype: InvoiceImportTypeInvoiceImportTransactions
        """
        return util.deserialize_model(dikt, cls)

    @property
    def invoice_import_transaction(self) -> List[InvoiceImportTransactionType]:
        """Gets the invoice_import_transaction of this InvoiceImportTypeInvoiceImportTransactions.


        :return: The invoice_import_transaction of this InvoiceImportTypeInvoiceImportTransactions.
        :rtype: List[InvoiceImportTransactionType]
        """
        return self._invoice_import_transaction

    @invoice_import_transaction.setter
    def invoice_import_transaction(self, invoice_import_transaction: List[InvoiceImportTransactionType]):
        """Sets the invoice_import_transaction of this InvoiceImportTypeInvoiceImportTransactions.


        :param invoice_import_transaction: The invoice_import_transaction of this InvoiceImportTypeInvoiceImportTransactions.
        :type invoice_import_transaction: List[InvoiceImportTransactionType]
        """

        self._invoice_import_transaction = invoice_import_transaction
