# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.invoice_line_amount_type import InvoiceLineAmountType  # noqa: F401,E501
from swagger_server import util


class InvoiceLineTypeAmounts(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, amount: List[InvoiceLineAmountType]=None):  # noqa: E501
        """InvoiceLineTypeAmounts - a model defined in Swagger

        :param amount: The amount of this InvoiceLineTypeAmounts.  # noqa: E501
        :type amount: List[InvoiceLineAmountType]
        """
        self.swagger_types = {
            'amount': List[InvoiceLineAmountType]
        }

        self.attribute_map = {
            'amount': 'amount'
        }
        self._amount = amount

    @classmethod
    def from_dict(cls, dikt) -> 'InvoiceLineTypeAmounts':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InvoiceLineType_amounts of this InvoiceLineTypeAmounts.  # noqa: E501
        :rtype: InvoiceLineTypeAmounts
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amount(self) -> List[InvoiceLineAmountType]:
        """Gets the amount of this InvoiceLineTypeAmounts.


        :return: The amount of this InvoiceLineTypeAmounts.
        :rtype: List[InvoiceLineAmountType]
        """
        return self._amount

    @amount.setter
    def amount(self, amount: List[InvoiceLineAmountType]):
        """Sets the amount of this InvoiceLineTypeAmounts.


        :param amount: The amount of this InvoiceLineTypeAmounts.
        :type amount: List[InvoiceLineAmountType]
        """

        self._amount = amount
