# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.allowance_info_type import AllowanceInfoType  # noqa: F401,E501
from swagger_server.models.institutional_info_type import InstitutionalInfoType  # noqa: F401,E501
from swagger_server.models.professional_info_type import ProfessionalInfoType  # noqa: F401,E501
from swagger_server import util


class InvoiceTypeInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, institutional_info: InstitutionalInfoType=None, professional_info: ProfessionalInfoType=None, allowance_info: AllowanceInfoType=None):  # noqa: E501
        """InvoiceTypeInfo - a model defined in Swagger

        :param institutional_info: The institutional_info of this InvoiceTypeInfo.  # noqa: E501
        :type institutional_info: InstitutionalInfoType
        :param professional_info: The professional_info of this InvoiceTypeInfo.  # noqa: E501
        :type professional_info: ProfessionalInfoType
        :param allowance_info: The allowance_info of this InvoiceTypeInfo.  # noqa: E501
        :type allowance_info: AllowanceInfoType
        """
        self.swagger_types = {
            'institutional_info': InstitutionalInfoType,
            'professional_info': ProfessionalInfoType,
            'allowance_info': AllowanceInfoType
        }

        self.attribute_map = {
            'institutional_info': 'institutionalInfo',
            'professional_info': 'professionalInfo',
            'allowance_info': 'allowanceInfo'
        }
        self._institutional_info = institutional_info
        self._professional_info = professional_info
        self._allowance_info = allowance_info

    @classmethod
    def from_dict(cls, dikt) -> 'InvoiceTypeInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The invoiceTypeInfo of this InvoiceTypeInfo.  # noqa: E501
        :rtype: InvoiceTypeInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def institutional_info(self) -> InstitutionalInfoType:
        """Gets the institutional_info of this InvoiceTypeInfo.


        :return: The institutional_info of this InvoiceTypeInfo.
        :rtype: InstitutionalInfoType
        """
        return self._institutional_info

    @institutional_info.setter
    def institutional_info(self, institutional_info: InstitutionalInfoType):
        """Sets the institutional_info of this InvoiceTypeInfo.


        :param institutional_info: The institutional_info of this InvoiceTypeInfo.
        :type institutional_info: InstitutionalInfoType
        """

        self._institutional_info = institutional_info

    @property
    def professional_info(self) -> ProfessionalInfoType:
        """Gets the professional_info of this InvoiceTypeInfo.


        :return: The professional_info of this InvoiceTypeInfo.
        :rtype: ProfessionalInfoType
        """
        return self._professional_info

    @professional_info.setter
    def professional_info(self, professional_info: ProfessionalInfoType):
        """Sets the professional_info of this InvoiceTypeInfo.


        :param professional_info: The professional_info of this InvoiceTypeInfo.
        :type professional_info: ProfessionalInfoType
        """

        self._professional_info = professional_info

    @property
    def allowance_info(self) -> AllowanceInfoType:
        """Gets the allowance_info of this InvoiceTypeInfo.


        :return: The allowance_info of this InvoiceTypeInfo.
        :rtype: AllowanceInfoType
        """
        return self._allowance_info

    @allowance_info.setter
    def allowance_info(self, allowance_info: AllowanceInfoType):
        """Sets the allowance_info of this InvoiceTypeInfo.


        :param allowance_info: The allowance_info of this InvoiceTypeInfo.
        :type allowance_info: AllowanceInfoType
        """

        self._allowance_info = allowance_info
