# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.note_type import NoteType  # noqa: F401,E501
from swagger_server import util


class InvoiceImportNoteType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, note_type: NoteType=None, deletion_user: str=None, deletion_date: datetime=None):  # noqa: E501
        """InvoiceImportNoteType - a model defined in Swagger

        :param note_type: The note_type of this InvoiceImportNoteType.  # noqa: E501
        :type note_type: NoteType
        :param deletion_user: The deletion_user of this InvoiceImportNoteType.  # noqa: E501
        :type deletion_user: str
        :param deletion_date: The deletion_date of this InvoiceImportNoteType.  # noqa: E501
        :type deletion_date: datetime
        """
        self.swagger_types = {
            'note_type': NoteType,
            'deletion_user': str,
            'deletion_date': datetime
        }

        self.attribute_map = {
            'note_type': 'noteType',
            'deletion_user': 'deletionUser',
            'deletion_date': 'deletionDate'
        }
        self._note_type = note_type
        self._deletion_user = deletion_user
        self._deletion_date = deletion_date

    @classmethod
    def from_dict(cls, dikt) -> 'InvoiceImportNoteType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InvoiceImportNoteType of this InvoiceImportNoteType.  # noqa: E501
        :rtype: InvoiceImportNoteType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def note_type(self) -> NoteType:
        """Gets the note_type of this InvoiceImportNoteType.


        :return: The note_type of this InvoiceImportNoteType.
        :rtype: NoteType
        """
        return self._note_type

    @note_type.setter
    def note_type(self, note_type: NoteType):
        """Sets the note_type of this InvoiceImportNoteType.


        :param note_type: The note_type of this InvoiceImportNoteType.
        :type note_type: NoteType
        """

        self._note_type = note_type

    @property
    def deletion_user(self) -> str:
        """Gets the deletion_user of this InvoiceImportNoteType.


        :return: The deletion_user of this InvoiceImportNoteType.
        :rtype: str
        """
        return self._deletion_user

    @deletion_user.setter
    def deletion_user(self, deletion_user: str):
        """Sets the deletion_user of this InvoiceImportNoteType.


        :param deletion_user: The deletion_user of this InvoiceImportNoteType.
        :type deletion_user: str
        """

        self._deletion_user = deletion_user

    @property
    def deletion_date(self) -> datetime:
        """Gets the deletion_date of this InvoiceImportNoteType.


        :return: The deletion_date of this InvoiceImportNoteType.
        :rtype: datetime
        """
        return self._deletion_date

    @deletion_date.setter
    def deletion_date(self, deletion_date: datetime):
        """Sets the deletion_date of this InvoiceImportNoteType.


        :param deletion_date: The deletion_date of this InvoiceImportNoteType.
        :type deletion_date: datetime
        """

        self._deletion_date = deletion_date
