# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.invoice_line_type import InvoiceLineType  # noqa: F401,E501
from swagger_server import util


class InvoiceTypeInvoiceLines(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, invoice_line: List[InvoiceLineType]=None):  # noqa: E501
        """InvoiceTypeInvoiceLines - a model defined in Swagger

        :param invoice_line: The invoice_line of this InvoiceTypeInvoiceLines.  # noqa: E501
        :type invoice_line: List[InvoiceLineType]
        """
        self.swagger_types = {
            'invoice_line': List[InvoiceLineType]
        }

        self.attribute_map = {
            'invoice_line': 'invoiceLine'
        }
        self._invoice_line = invoice_line

    @classmethod
    def from_dict(cls, dikt) -> 'InvoiceTypeInvoiceLines':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InvoiceType_invoiceLines of this InvoiceTypeInvoiceLines.  # noqa: E501
        :rtype: InvoiceTypeInvoiceLines
        """
        return util.deserialize_model(dikt, cls)

    @property
    def invoice_line(self) -> List[InvoiceLineType]:
        """Gets the invoice_line of this InvoiceTypeInvoiceLines.


        :return: The invoice_line of this InvoiceTypeInvoiceLines.
        :rtype: List[InvoiceLineType]
        """
        return self._invoice_line

    @invoice_line.setter
    def invoice_line(self, invoice_line: List[InvoiceLineType]):
        """Sets the invoice_line of this InvoiceTypeInvoiceLines.


        :param invoice_line: The invoice_line of this InvoiceTypeInvoiceLines.
        :type invoice_line: List[InvoiceLineType]
        """

        self._invoice_line = invoice_line
