# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.amount_type import AmountType  # noqa: F401,E501
from swagger_server.models.applied_level_type import AppliedLevelType  # noqa: F401,E501
from swagger_server import util


class InvoiceTransactionType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, invoice_nbr: int=None, invoice_status_id: str=None, policy_nbr: int=None, insurance_company_nbr: int=None, principal_nbr: int=None, member_nbr: int=None, invoice_line_nbr: int=None, case_nbr: int=None, incident_nbr: int=None, claim_nbr: int=None, coverage_criterion_nbr: int=None, coverage_rule_nbr: int=None, package_rule_nbr: int=None, applied_level: AppliedLevelType=None, leveid: int=None, rule_start_date: datetime=None, rule_stop_date: datetime=None, rule_extend_nbr: int=None, actual_copay_amount: AmountType=None, insured_amount: AmountType=None, insurer_amount: AmountType=None, product_currency_id: int=None, insured_quantity: float=None, insurer_quantity: float=None, quantity_qualifier_id: str=None):  # noqa: E501
        """InvoiceTransactionType - a model defined in Swagger

        :param invoice_nbr: The invoice_nbr of this InvoiceTransactionType.  # noqa: E501
        :type invoice_nbr: int
        :param invoice_status_id: The invoice_status_id of this InvoiceTransactionType.  # noqa: E501
        :type invoice_status_id: str
        :param policy_nbr: The policy_nbr of this InvoiceTransactionType.  # noqa: E501
        :type policy_nbr: int
        :param insurance_company_nbr: The insurance_company_nbr of this InvoiceTransactionType.  # noqa: E501
        :type insurance_company_nbr: int
        :param principal_nbr: The principal_nbr of this InvoiceTransactionType.  # noqa: E501
        :type principal_nbr: int
        :param member_nbr: The member_nbr of this InvoiceTransactionType.  # noqa: E501
        :type member_nbr: int
        :param invoice_line_nbr: The invoice_line_nbr of this InvoiceTransactionType.  # noqa: E501
        :type invoice_line_nbr: int
        :param case_nbr: The case_nbr of this InvoiceTransactionType.  # noqa: E501
        :type case_nbr: int
        :param incident_nbr: The incident_nbr of this InvoiceTransactionType.  # noqa: E501
        :type incident_nbr: int
        :param claim_nbr: The claim_nbr of this InvoiceTransactionType.  # noqa: E501
        :type claim_nbr: int
        :param coverage_criterion_nbr: The coverage_criterion_nbr of this InvoiceTransactionType.  # noqa: E501
        :type coverage_criterion_nbr: int
        :param coverage_rule_nbr: The coverage_rule_nbr of this InvoiceTransactionType.  # noqa: E501
        :type coverage_rule_nbr: int
        :param package_rule_nbr: The package_rule_nbr of this InvoiceTransactionType.  # noqa: E501
        :type package_rule_nbr: int
        :param applied_level: The applied_level of this InvoiceTransactionType.  # noqa: E501
        :type applied_level: AppliedLevelType
        :param leveid: The leveid of this InvoiceTransactionType.  # noqa: E501
        :type leveid: int
        :param rule_start_date: The rule_start_date of this InvoiceTransactionType.  # noqa: E501
        :type rule_start_date: datetime
        :param rule_stop_date: The rule_stop_date of this InvoiceTransactionType.  # noqa: E501
        :type rule_stop_date: datetime
        :param rule_extend_nbr: The rule_extend_nbr of this InvoiceTransactionType.  # noqa: E501
        :type rule_extend_nbr: int
        :param actual_copay_amount: The actual_copay_amount of this InvoiceTransactionType.  # noqa: E501
        :type actual_copay_amount: AmountType
        :param insured_amount: The insured_amount of this InvoiceTransactionType.  # noqa: E501
        :type insured_amount: AmountType
        :param insurer_amount: The insurer_amount of this InvoiceTransactionType.  # noqa: E501
        :type insurer_amount: AmountType
        :param product_currency_id: The product_currency_id of this InvoiceTransactionType.  # noqa: E501
        :type product_currency_id: int
        :param insured_quantity: The insured_quantity of this InvoiceTransactionType.  # noqa: E501
        :type insured_quantity: float
        :param insurer_quantity: The insurer_quantity of this InvoiceTransactionType.  # noqa: E501
        :type insurer_quantity: float
        :param quantity_qualifier_id: The quantity_qualifier_id of this InvoiceTransactionType.  # noqa: E501
        :type quantity_qualifier_id: str
        """
        self.swagger_types = {
            'invoice_nbr': int,
            'invoice_status_id': str,
            'policy_nbr': int,
            'insurance_company_nbr': int,
            'principal_nbr': int,
            'member_nbr': int,
            'invoice_line_nbr': int,
            'case_nbr': int,
            'incident_nbr': int,
            'claim_nbr': int,
            'coverage_criterion_nbr': int,
            'coverage_rule_nbr': int,
            'package_rule_nbr': int,
            'applied_level': AppliedLevelType,
            'leveid': int,
            'rule_start_date': datetime,
            'rule_stop_date': datetime,
            'rule_extend_nbr': int,
            'actual_copay_amount': AmountType,
            'insured_amount': AmountType,
            'insurer_amount': AmountType,
            'product_currency_id': int,
            'insured_quantity': float,
            'insurer_quantity': float,
            'quantity_qualifier_id': str
        }

        self.attribute_map = {
            'invoice_nbr': 'invoiceNbr',
            'invoice_status_id': 'invoiceStatusId',
            'policy_nbr': 'policyNbr',
            'insurance_company_nbr': 'insuranceCompanyNbr',
            'principal_nbr': 'principalNbr',
            'member_nbr': 'memberNbr',
            'invoice_line_nbr': 'invoiceLineNbr',
            'case_nbr': 'caseNbr',
            'incident_nbr': 'incidentNbr',
            'claim_nbr': 'claimNbr',
            'coverage_criterion_nbr': 'coverageCriterionNbr',
            'coverage_rule_nbr': 'coverageRuleNbr',
            'package_rule_nbr': 'packageRuleNbr',
            'applied_level': 'appliedLevel',
            'leveid': 'leveid',
            'rule_start_date': 'ruleStartDate',
            'rule_stop_date': 'ruleStopDate',
            'rule_extend_nbr': 'ruleExtendNbr',
            'actual_copay_amount': 'actualCopayAmount',
            'insured_amount': 'insuredAmount',
            'insurer_amount': 'insurerAmount',
            'product_currency_id': 'productCurrencyId',
            'insured_quantity': 'insuredQuantity',
            'insurer_quantity': 'insurerQuantity',
            'quantity_qualifier_id': 'quantityQualifierId'
        }
        self._invoice_nbr = invoice_nbr
        self._invoice_status_id = invoice_status_id
        self._policy_nbr = policy_nbr
        self._insurance_company_nbr = insurance_company_nbr
        self._principal_nbr = principal_nbr
        self._member_nbr = member_nbr
        self._invoice_line_nbr = invoice_line_nbr
        self._case_nbr = case_nbr
        self._incident_nbr = incident_nbr
        self._claim_nbr = claim_nbr
        self._coverage_criterion_nbr = coverage_criterion_nbr
        self._coverage_rule_nbr = coverage_rule_nbr
        self._package_rule_nbr = package_rule_nbr
        self._applied_level = applied_level
        self._leveid = leveid
        self._rule_start_date = rule_start_date
        self._rule_stop_date = rule_stop_date
        self._rule_extend_nbr = rule_extend_nbr
        self._actual_copay_amount = actual_copay_amount
        self._insured_amount = insured_amount
        self._insurer_amount = insurer_amount
        self._product_currency_id = product_currency_id
        self._insured_quantity = insured_quantity
        self._insurer_quantity = insurer_quantity
        self._quantity_qualifier_id = quantity_qualifier_id

    @classmethod
    def from_dict(cls, dikt) -> 'InvoiceTransactionType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InvoiceTransactionType of this InvoiceTransactionType.  # noqa: E501
        :rtype: InvoiceTransactionType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def invoice_nbr(self) -> int:
        """Gets the invoice_nbr of this InvoiceTransactionType.


        :return: The invoice_nbr of this InvoiceTransactionType.
        :rtype: int
        """
        return self._invoice_nbr

    @invoice_nbr.setter
    def invoice_nbr(self, invoice_nbr: int):
        """Sets the invoice_nbr of this InvoiceTransactionType.


        :param invoice_nbr: The invoice_nbr of this InvoiceTransactionType.
        :type invoice_nbr: int
        """

        self._invoice_nbr = invoice_nbr

    @property
    def invoice_status_id(self) -> str:
        """Gets the invoice_status_id of this InvoiceTransactionType.


        :return: The invoice_status_id of this InvoiceTransactionType.
        :rtype: str
        """
        return self._invoice_status_id

    @invoice_status_id.setter
    def invoice_status_id(self, invoice_status_id: str):
        """Sets the invoice_status_id of this InvoiceTransactionType.


        :param invoice_status_id: The invoice_status_id of this InvoiceTransactionType.
        :type invoice_status_id: str
        """

        self._invoice_status_id = invoice_status_id

    @property
    def policy_nbr(self) -> int:
        """Gets the policy_nbr of this InvoiceTransactionType.


        :return: The policy_nbr of this InvoiceTransactionType.
        :rtype: int
        """
        return self._policy_nbr

    @policy_nbr.setter
    def policy_nbr(self, policy_nbr: int):
        """Sets the policy_nbr of this InvoiceTransactionType.


        :param policy_nbr: The policy_nbr of this InvoiceTransactionType.
        :type policy_nbr: int
        """

        self._policy_nbr = policy_nbr

    @property
    def insurance_company_nbr(self) -> int:
        """Gets the insurance_company_nbr of this InvoiceTransactionType.


        :return: The insurance_company_nbr of this InvoiceTransactionType.
        :rtype: int
        """
        return self._insurance_company_nbr

    @insurance_company_nbr.setter
    def insurance_company_nbr(self, insurance_company_nbr: int):
        """Sets the insurance_company_nbr of this InvoiceTransactionType.


        :param insurance_company_nbr: The insurance_company_nbr of this InvoiceTransactionType.
        :type insurance_company_nbr: int
        """

        self._insurance_company_nbr = insurance_company_nbr

    @property
    def principal_nbr(self) -> int:
        """Gets the principal_nbr of this InvoiceTransactionType.


        :return: The principal_nbr of this InvoiceTransactionType.
        :rtype: int
        """
        return self._principal_nbr

    @principal_nbr.setter
    def principal_nbr(self, principal_nbr: int):
        """Sets the principal_nbr of this InvoiceTransactionType.


        :param principal_nbr: The principal_nbr of this InvoiceTransactionType.
        :type principal_nbr: int
        """

        self._principal_nbr = principal_nbr

    @property
    def member_nbr(self) -> int:
        """Gets the member_nbr of this InvoiceTransactionType.


        :return: The member_nbr of this InvoiceTransactionType.
        :rtype: int
        """
        return self._member_nbr

    @member_nbr.setter
    def member_nbr(self, member_nbr: int):
        """Sets the member_nbr of this InvoiceTransactionType.


        :param member_nbr: The member_nbr of this InvoiceTransactionType.
        :type member_nbr: int
        """

        self._member_nbr = member_nbr

    @property
    def invoice_line_nbr(self) -> int:
        """Gets the invoice_line_nbr of this InvoiceTransactionType.


        :return: The invoice_line_nbr of this InvoiceTransactionType.
        :rtype: int
        """
        return self._invoice_line_nbr

    @invoice_line_nbr.setter
    def invoice_line_nbr(self, invoice_line_nbr: int):
        """Sets the invoice_line_nbr of this InvoiceTransactionType.


        :param invoice_line_nbr: The invoice_line_nbr of this InvoiceTransactionType.
        :type invoice_line_nbr: int
        """

        self._invoice_line_nbr = invoice_line_nbr

    @property
    def case_nbr(self) -> int:
        """Gets the case_nbr of this InvoiceTransactionType.


        :return: The case_nbr of this InvoiceTransactionType.
        :rtype: int
        """
        return self._case_nbr

    @case_nbr.setter
    def case_nbr(self, case_nbr: int):
        """Sets the case_nbr of this InvoiceTransactionType.


        :param case_nbr: The case_nbr of this InvoiceTransactionType.
        :type case_nbr: int
        """

        self._case_nbr = case_nbr

    @property
    def incident_nbr(self) -> int:
        """Gets the incident_nbr of this InvoiceTransactionType.


        :return: The incident_nbr of this InvoiceTransactionType.
        :rtype: int
        """
        return self._incident_nbr

    @incident_nbr.setter
    def incident_nbr(self, incident_nbr: int):
        """Sets the incident_nbr of this InvoiceTransactionType.


        :param incident_nbr: The incident_nbr of this InvoiceTransactionType.
        :type incident_nbr: int
        """

        self._incident_nbr = incident_nbr

    @property
    def claim_nbr(self) -> int:
        """Gets the claim_nbr of this InvoiceTransactionType.


        :return: The claim_nbr of this InvoiceTransactionType.
        :rtype: int
        """
        return self._claim_nbr

    @claim_nbr.setter
    def claim_nbr(self, claim_nbr: int):
        """Sets the claim_nbr of this InvoiceTransactionType.


        :param claim_nbr: The claim_nbr of this InvoiceTransactionType.
        :type claim_nbr: int
        """

        self._claim_nbr = claim_nbr

    @property
    def coverage_criterion_nbr(self) -> int:
        """Gets the coverage_criterion_nbr of this InvoiceTransactionType.


        :return: The coverage_criterion_nbr of this InvoiceTransactionType.
        :rtype: int
        """
        return self._coverage_criterion_nbr

    @coverage_criterion_nbr.setter
    def coverage_criterion_nbr(self, coverage_criterion_nbr: int):
        """Sets the coverage_criterion_nbr of this InvoiceTransactionType.


        :param coverage_criterion_nbr: The coverage_criterion_nbr of this InvoiceTransactionType.
        :type coverage_criterion_nbr: int
        """

        self._coverage_criterion_nbr = coverage_criterion_nbr

    @property
    def coverage_rule_nbr(self) -> int:
        """Gets the coverage_rule_nbr of this InvoiceTransactionType.


        :return: The coverage_rule_nbr of this InvoiceTransactionType.
        :rtype: int
        """
        return self._coverage_rule_nbr

    @coverage_rule_nbr.setter
    def coverage_rule_nbr(self, coverage_rule_nbr: int):
        """Sets the coverage_rule_nbr of this InvoiceTransactionType.


        :param coverage_rule_nbr: The coverage_rule_nbr of this InvoiceTransactionType.
        :type coverage_rule_nbr: int
        """

        self._coverage_rule_nbr = coverage_rule_nbr

    @property
    def package_rule_nbr(self) -> int:
        """Gets the package_rule_nbr of this InvoiceTransactionType.


        :return: The package_rule_nbr of this InvoiceTransactionType.
        :rtype: int
        """
        return self._package_rule_nbr

    @package_rule_nbr.setter
    def package_rule_nbr(self, package_rule_nbr: int):
        """Sets the package_rule_nbr of this InvoiceTransactionType.


        :param package_rule_nbr: The package_rule_nbr of this InvoiceTransactionType.
        :type package_rule_nbr: int
        """

        self._package_rule_nbr = package_rule_nbr

    @property
    def applied_level(self) -> AppliedLevelType:
        """Gets the applied_level of this InvoiceTransactionType.


        :return: The applied_level of this InvoiceTransactionType.
        :rtype: AppliedLevelType
        """
        return self._applied_level

    @applied_level.setter
    def applied_level(self, applied_level: AppliedLevelType):
        """Sets the applied_level of this InvoiceTransactionType.


        :param applied_level: The applied_level of this InvoiceTransactionType.
        :type applied_level: AppliedLevelType
        """

        self._applied_level = applied_level

    @property
    def leveid(self) -> int:
        """Gets the leveid of this InvoiceTransactionType.


        :return: The leveid of this InvoiceTransactionType.
        :rtype: int
        """
        return self._leveid

    @leveid.setter
    def leveid(self, leveid: int):
        """Sets the leveid of this InvoiceTransactionType.


        :param leveid: The leveid of this InvoiceTransactionType.
        :type leveid: int
        """

        self._leveid = leveid

    @property
    def rule_start_date(self) -> datetime:
        """Gets the rule_start_date of this InvoiceTransactionType.


        :return: The rule_start_date of this InvoiceTransactionType.
        :rtype: datetime
        """
        return self._rule_start_date

    @rule_start_date.setter
    def rule_start_date(self, rule_start_date: datetime):
        """Sets the rule_start_date of this InvoiceTransactionType.


        :param rule_start_date: The rule_start_date of this InvoiceTransactionType.
        :type rule_start_date: datetime
        """

        self._rule_start_date = rule_start_date

    @property
    def rule_stop_date(self) -> datetime:
        """Gets the rule_stop_date of this InvoiceTransactionType.


        :return: The rule_stop_date of this InvoiceTransactionType.
        :rtype: datetime
        """
        return self._rule_stop_date

    @rule_stop_date.setter
    def rule_stop_date(self, rule_stop_date: datetime):
        """Sets the rule_stop_date of this InvoiceTransactionType.


        :param rule_stop_date: The rule_stop_date of this InvoiceTransactionType.
        :type rule_stop_date: datetime
        """

        self._rule_stop_date = rule_stop_date

    @property
    def rule_extend_nbr(self) -> int:
        """Gets the rule_extend_nbr of this InvoiceTransactionType.


        :return: The rule_extend_nbr of this InvoiceTransactionType.
        :rtype: int
        """
        return self._rule_extend_nbr

    @rule_extend_nbr.setter
    def rule_extend_nbr(self, rule_extend_nbr: int):
        """Sets the rule_extend_nbr of this InvoiceTransactionType.


        :param rule_extend_nbr: The rule_extend_nbr of this InvoiceTransactionType.
        :type rule_extend_nbr: int
        """

        self._rule_extend_nbr = rule_extend_nbr

    @property
    def actual_copay_amount(self) -> AmountType:
        """Gets the actual_copay_amount of this InvoiceTransactionType.


        :return: The actual_copay_amount of this InvoiceTransactionType.
        :rtype: AmountType
        """
        return self._actual_copay_amount

    @actual_copay_amount.setter
    def actual_copay_amount(self, actual_copay_amount: AmountType):
        """Sets the actual_copay_amount of this InvoiceTransactionType.


        :param actual_copay_amount: The actual_copay_amount of this InvoiceTransactionType.
        :type actual_copay_amount: AmountType
        """

        self._actual_copay_amount = actual_copay_amount

    @property
    def insured_amount(self) -> AmountType:
        """Gets the insured_amount of this InvoiceTransactionType.


        :return: The insured_amount of this InvoiceTransactionType.
        :rtype: AmountType
        """
        return self._insured_amount

    @insured_amount.setter
    def insured_amount(self, insured_amount: AmountType):
        """Sets the insured_amount of this InvoiceTransactionType.


        :param insured_amount: The insured_amount of this InvoiceTransactionType.
        :type insured_amount: AmountType
        """

        self._insured_amount = insured_amount

    @property
    def insurer_amount(self) -> AmountType:
        """Gets the insurer_amount of this InvoiceTransactionType.


        :return: The insurer_amount of this InvoiceTransactionType.
        :rtype: AmountType
        """
        return self._insurer_amount

    @insurer_amount.setter
    def insurer_amount(self, insurer_amount: AmountType):
        """Sets the insurer_amount of this InvoiceTransactionType.


        :param insurer_amount: The insurer_amount of this InvoiceTransactionType.
        :type insurer_amount: AmountType
        """

        self._insurer_amount = insurer_amount

    @property
    def product_currency_id(self) -> int:
        """Gets the product_currency_id of this InvoiceTransactionType.


        :return: The product_currency_id of this InvoiceTransactionType.
        :rtype: int
        """
        return self._product_currency_id

    @product_currency_id.setter
    def product_currency_id(self, product_currency_id: int):
        """Sets the product_currency_id of this InvoiceTransactionType.


        :param product_currency_id: The product_currency_id of this InvoiceTransactionType.
        :type product_currency_id: int
        """

        self._product_currency_id = product_currency_id

    @property
    def insured_quantity(self) -> float:
        """Gets the insured_quantity of this InvoiceTransactionType.


        :return: The insured_quantity of this InvoiceTransactionType.
        :rtype: float
        """
        return self._insured_quantity

    @insured_quantity.setter
    def insured_quantity(self, insured_quantity: float):
        """Sets the insured_quantity of this InvoiceTransactionType.


        :param insured_quantity: The insured_quantity of this InvoiceTransactionType.
        :type insured_quantity: float
        """

        self._insured_quantity = insured_quantity

    @property
    def insurer_quantity(self) -> float:
        """Gets the insurer_quantity of this InvoiceTransactionType.


        :return: The insurer_quantity of this InvoiceTransactionType.
        :rtype: float
        """
        return self._insurer_quantity

    @insurer_quantity.setter
    def insurer_quantity(self, insurer_quantity: float):
        """Sets the insurer_quantity of this InvoiceTransactionType.


        :param insurer_quantity: The insurer_quantity of this InvoiceTransactionType.
        :type insurer_quantity: float
        """

        self._insurer_quantity = insurer_quantity

    @property
    def quantity_qualifier_id(self) -> str:
        """Gets the quantity_qualifier_id of this InvoiceTransactionType.


        :return: The quantity_qualifier_id of this InvoiceTransactionType.
        :rtype: str
        """
        return self._quantity_qualifier_id

    @quantity_qualifier_id.setter
    def quantity_qualifier_id(self, quantity_qualifier_id: str):
        """Sets the quantity_qualifier_id of this InvoiceTransactionType.


        :param quantity_qualifier_id: The quantity_qualifier_id of this InvoiceTransactionType.
        :type quantity_qualifier_id: str
        """

        self._quantity_qualifier_id = quantity_qualifier_id
