# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OutpatientInfoType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, perscription_date: datetime=None):  # noqa: E501
        """OutpatientInfoType - a model defined in Swagger

        :param perscription_date: The perscription_date of this OutpatientInfoType.  # noqa: E501
        :type perscription_date: datetime
        """
        self.swagger_types = {
            'perscription_date': datetime
        }

        self.attribute_map = {
            'perscription_date': 'perscriptionDate'
        }
        self._perscription_date = perscription_date

    @classmethod
    def from_dict(cls, dikt) -> 'OutpatientInfoType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OutpatientInfoType of this OutpatientInfoType.  # noqa: E501
        :rtype: OutpatientInfoType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def perscription_date(self) -> datetime:
        """Gets the perscription_date of this OutpatientInfoType.


        :return: The perscription_date of this OutpatientInfoType.
        :rtype: datetime
        """
        return self._perscription_date

    @perscription_date.setter
    def perscription_date(self, perscription_date: datetime):
        """Sets the perscription_date of this OutpatientInfoType.


        :param perscription_date: The perscription_date of this OutpatientInfoType.
        :type perscription_date: datetime
        """

        self._perscription_date = perscription_date
