# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.claim_status_item_type import ClaimStatusItemType  # noqa: F401,E501
from swagger_server import util


class PerformClaimModifyStatusBPSCBMType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, claim_status_item: ClaimStatusItemType=None):  # noqa: E501
        """PerformClaimModifyStatusBPSCBMType - a model defined in Swagger

        :param claim_status_item: The claim_status_item of this PerformClaimModifyStatusBPSCBMType.  # noqa: E501
        :type claim_status_item: ClaimStatusItemType
        """
        self.swagger_types = {
            'claim_status_item': ClaimStatusItemType
        }

        self.attribute_map = {
            'claim_status_item': 'claimStatusItem'
        }
        self._claim_status_item = claim_status_item

    @classmethod
    def from_dict(cls, dikt) -> 'PerformClaimModifyStatusBPSCBMType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PerformClaimModifyStatusBPSCBMType of this PerformClaimModifyStatusBPSCBMType.  # noqa: E501
        :rtype: PerformClaimModifyStatusBPSCBMType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def claim_status_item(self) -> ClaimStatusItemType:
        """Gets the claim_status_item of this PerformClaimModifyStatusBPSCBMType.


        :return: The claim_status_item of this PerformClaimModifyStatusBPSCBMType.
        :rtype: ClaimStatusItemType
        """
        return self._claim_status_item

    @claim_status_item.setter
    def claim_status_item(self, claim_status_item: ClaimStatusItemType):
        """Sets the claim_status_item of this PerformClaimModifyStatusBPSCBMType.


        :param claim_status_item: The claim_status_item of this PerformClaimModifyStatusBPSCBMType.
        :type claim_status_item: ClaimStatusItemType
        """
        if claim_status_item is None:
            raise ValueError("Invalid value for `claim_status_item`, must not be `None`")  # noqa: E501

        self._claim_status_item = claim_status_item
