# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.create_claim_item_type import CreateClaimItemType  # noqa: F401,E501
from swagger_server import util


class PerformClaimCreationBPSCBMType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, claim_item: CreateClaimItemType=None):  # noqa: E501
        """PerformClaimCreationBPSCBMType - a model defined in Swagger

        :param claim_item: The claim_item of this PerformClaimCreationBPSCBMType.  # noqa: E501
        :type claim_item: CreateClaimItemType
        """
        self.swagger_types = {
            'claim_item': CreateClaimItemType
        }

        self.attribute_map = {
            'claim_item': 'claimItem'
        }
        self._claim_item = claim_item

    @classmethod
    def from_dict(cls, dikt) -> 'PerformClaimCreationBPSCBMType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PerformClaimCreationBPSCBMType of this PerformClaimCreationBPSCBMType.  # noqa: E501
        :rtype: PerformClaimCreationBPSCBMType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def claim_item(self) -> CreateClaimItemType:
        """Gets the claim_item of this PerformClaimCreationBPSCBMType.


        :return: The claim_item of this PerformClaimCreationBPSCBMType.
        :rtype: CreateClaimItemType
        """
        return self._claim_item

    @claim_item.setter
    def claim_item(self, claim_item: CreateClaimItemType):
        """Sets the claim_item of this PerformClaimCreationBPSCBMType.


        :param claim_item: The claim_item of this PerformClaimCreationBPSCBMType.
        :type claim_item: CreateClaimItemType
        """
        if claim_item is None:
            raise ValueError("Invalid value for `claim_item`, must not be `None`")  # noqa: E501

        self._claim_item = claim_item
