# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class QueryByIdCBMType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, claim_nbr: int=None):  # noqa: E501
        """QueryByIdCBMType - a model defined in Swagger

        :param claim_nbr: The claim_nbr of this QueryByIdCBMType.  # noqa: E501
        :type claim_nbr: int
        """
        self.swagger_types = {
            'claim_nbr': int
        }

        self.attribute_map = {
            'claim_nbr': 'claimNbr'
        }
        self._claim_nbr = claim_nbr

    @classmethod
    def from_dict(cls, dikt) -> 'QueryByIdCBMType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QueryByIdCBMType of this QueryByIdCBMType.  # noqa: E501
        :rtype: QueryByIdCBMType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def claim_nbr(self) -> int:
        """Gets the claim_nbr of this QueryByIdCBMType.


        :return: The claim_nbr of this QueryByIdCBMType.
        :rtype: int
        """
        return self._claim_nbr

    @claim_nbr.setter
    def claim_nbr(self, claim_nbr: int):
        """Sets the claim_nbr of this QueryByIdCBMType.


        :param claim_nbr: The claim_nbr of this QueryByIdCBMType.
        :type claim_nbr: int
        """

        self._claim_nbr = claim_nbr
