# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.claim_type import ClaimType  # noqa: F401,E501
from swagger_server.models.error_info_type import ErrorInfoType  # noqa: F401,E501
from swagger_server import util


class QueryByIdResponseCBMType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error_info_type: ErrorInfoType=None, claim: ClaimType=None):  # noqa: E501
        """QueryByIdResponseCBMType - a model defined in Swagger

        :param error_info_type: The error_info_type of this QueryByIdResponseCBMType.  # noqa: E501
        :type error_info_type: ErrorInfoType
        :param claim: The claim of this QueryByIdResponseCBMType.  # noqa: E501
        :type claim: ClaimType
        """
        self.swagger_types = {
            'error_info_type': ErrorInfoType,
            'claim': ClaimType
        }

        self.attribute_map = {
            'error_info_type': 'errorInfoType',
            'claim': 'claim'
        }
        self._error_info_type = error_info_type
        self._claim = claim

    @classmethod
    def from_dict(cls, dikt) -> 'QueryByIdResponseCBMType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QueryByIdResponseCBMType of this QueryByIdResponseCBMType.  # noqa: E501
        :rtype: QueryByIdResponseCBMType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_info_type(self) -> ErrorInfoType:
        """Gets the error_info_type of this QueryByIdResponseCBMType.


        :return: The error_info_type of this QueryByIdResponseCBMType.
        :rtype: ErrorInfoType
        """
        return self._error_info_type

    @error_info_type.setter
    def error_info_type(self, error_info_type: ErrorInfoType):
        """Sets the error_info_type of this QueryByIdResponseCBMType.


        :param error_info_type: The error_info_type of this QueryByIdResponseCBMType.
        :type error_info_type: ErrorInfoType
        """

        self._error_info_type = error_info_type

    @property
    def claim(self) -> ClaimType:
        """Gets the claim of this QueryByIdResponseCBMType.


        :return: The claim of this QueryByIdResponseCBMType.
        :rtype: ClaimType
        """
        return self._claim

    @claim.setter
    def claim(self, claim: ClaimType):
        """Sets the claim of this QueryByIdResponseCBMType.


        :param claim: The claim of this QueryByIdResponseCBMType.
        :type claim: ClaimType
        """

        self._claim = claim
