# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.queue_item_type_error_detail_list import QueueItemTypeErrorDetailList  # noqa: F401,E501
from swagger_server.models.queue_item_type_sub_item_list import QueueItemTypeSubItemList  # noqa: F401,E501
from swagger_server.models.queue_status_type import QueueStatusType  # noqa: F401,E501
from swagger_server.models.resource_verb_type import ResourceVerbType  # noqa: F401,E501
from swagger_server import util


class QueueItemType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, queue_nbr: int=None, external_reference: str=None, queue_parent_nbr: int=None, queue_item_nbr: int=None, resource_path: str=None, resource_verb: ResourceVerbType=None, resource_id: str=None, creation_date: datetime=None, modification_date: datetime=None, error_code: str=None, error_message: str=None, status: QueueStatusType=None, error_detail_list: QueueItemTypeErrorDetailList=None, sub_item_list: QueueItemTypeSubItemList=None):  # noqa: E501
        """QueueItemType - a model defined in Swagger

        :param queue_nbr: The queue_nbr of this QueueItemType.  # noqa: E501
        :type queue_nbr: int
        :param external_reference: The external_reference of this QueueItemType.  # noqa: E501
        :type external_reference: str
        :param queue_parent_nbr: The queue_parent_nbr of this QueueItemType.  # noqa: E501
        :type queue_parent_nbr: int
        :param queue_item_nbr: The queue_item_nbr of this QueueItemType.  # noqa: E501
        :type queue_item_nbr: int
        :param resource_path: The resource_path of this QueueItemType.  # noqa: E501
        :type resource_path: str
        :param resource_verb: The resource_verb of this QueueItemType.  # noqa: E501
        :type resource_verb: ResourceVerbType
        :param resource_id: The resource_id of this QueueItemType.  # noqa: E501
        :type resource_id: str
        :param creation_date: The creation_date of this QueueItemType.  # noqa: E501
        :type creation_date: datetime
        :param modification_date: The modification_date of this QueueItemType.  # noqa: E501
        :type modification_date: datetime
        :param error_code: The error_code of this QueueItemType.  # noqa: E501
        :type error_code: str
        :param error_message: The error_message of this QueueItemType.  # noqa: E501
        :type error_message: str
        :param status: The status of this QueueItemType.  # noqa: E501
        :type status: QueueStatusType
        :param error_detail_list: The error_detail_list of this QueueItemType.  # noqa: E501
        :type error_detail_list: QueueItemTypeErrorDetailList
        :param sub_item_list: The sub_item_list of this QueueItemType.  # noqa: E501
        :type sub_item_list: QueueItemTypeSubItemList
        """
        self.swagger_types = {
            'queue_nbr': int,
            'external_reference': str,
            'queue_parent_nbr': int,
            'queue_item_nbr': int,
            'resource_path': str,
            'resource_verb': ResourceVerbType,
            'resource_id': str,
            'creation_date': datetime,
            'modification_date': datetime,
            'error_code': str,
            'error_message': str,
            'status': QueueStatusType,
            'error_detail_list': QueueItemTypeErrorDetailList,
            'sub_item_list': QueueItemTypeSubItemList
        }

        self.attribute_map = {
            'queue_nbr': 'queueNbr',
            'external_reference': 'externalReference',
            'queue_parent_nbr': 'queueParentNbr',
            'queue_item_nbr': 'queueItemNbr',
            'resource_path': 'resourcePath',
            'resource_verb': 'resourceVerb',
            'resource_id': 'resourceId',
            'creation_date': 'creationDate',
            'modification_date': 'modificationDate',
            'error_code': 'errorCode',
            'error_message': 'errorMessage',
            'status': 'status',
            'error_detail_list': 'errorDetailList',
            'sub_item_list': 'subItemList'
        }
        self._queue_nbr = queue_nbr
        self._external_reference = external_reference
        self._queue_parent_nbr = queue_parent_nbr
        self._queue_item_nbr = queue_item_nbr
        self._resource_path = resource_path
        self._resource_verb = resource_verb
        self._resource_id = resource_id
        self._creation_date = creation_date
        self._modification_date = modification_date
        self._error_code = error_code
        self._error_message = error_message
        self._status = status
        self._error_detail_list = error_detail_list
        self._sub_item_list = sub_item_list

    @classmethod
    def from_dict(cls, dikt) -> 'QueueItemType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QueueItemType of this QueueItemType.  # noqa: E501
        :rtype: QueueItemType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def queue_nbr(self) -> int:
        """Gets the queue_nbr of this QueueItemType.


        :return: The queue_nbr of this QueueItemType.
        :rtype: int
        """
        return self._queue_nbr

    @queue_nbr.setter
    def queue_nbr(self, queue_nbr: int):
        """Sets the queue_nbr of this QueueItemType.


        :param queue_nbr: The queue_nbr of this QueueItemType.
        :type queue_nbr: int
        """

        self._queue_nbr = queue_nbr

    @property
    def external_reference(self) -> str:
        """Gets the external_reference of this QueueItemType.


        :return: The external_reference of this QueueItemType.
        :rtype: str
        """
        return self._external_reference

    @external_reference.setter
    def external_reference(self, external_reference: str):
        """Sets the external_reference of this QueueItemType.


        :param external_reference: The external_reference of this QueueItemType.
        :type external_reference: str
        """

        self._external_reference = external_reference

    @property
    def queue_parent_nbr(self) -> int:
        """Gets the queue_parent_nbr of this QueueItemType.


        :return: The queue_parent_nbr of this QueueItemType.
        :rtype: int
        """
        return self._queue_parent_nbr

    @queue_parent_nbr.setter
    def queue_parent_nbr(self, queue_parent_nbr: int):
        """Sets the queue_parent_nbr of this QueueItemType.


        :param queue_parent_nbr: The queue_parent_nbr of this QueueItemType.
        :type queue_parent_nbr: int
        """

        self._queue_parent_nbr = queue_parent_nbr

    @property
    def queue_item_nbr(self) -> int:
        """Gets the queue_item_nbr of this QueueItemType.


        :return: The queue_item_nbr of this QueueItemType.
        :rtype: int
        """
        return self._queue_item_nbr

    @queue_item_nbr.setter
    def queue_item_nbr(self, queue_item_nbr: int):
        """Sets the queue_item_nbr of this QueueItemType.


        :param queue_item_nbr: The queue_item_nbr of this QueueItemType.
        :type queue_item_nbr: int
        """

        self._queue_item_nbr = queue_item_nbr

    @property
    def resource_path(self) -> str:
        """Gets the resource_path of this QueueItemType.


        :return: The resource_path of this QueueItemType.
        :rtype: str
        """
        return self._resource_path

    @resource_path.setter
    def resource_path(self, resource_path: str):
        """Sets the resource_path of this QueueItemType.


        :param resource_path: The resource_path of this QueueItemType.
        :type resource_path: str
        """

        self._resource_path = resource_path

    @property
    def resource_verb(self) -> ResourceVerbType:
        """Gets the resource_verb of this QueueItemType.


        :return: The resource_verb of this QueueItemType.
        :rtype: ResourceVerbType
        """
        return self._resource_verb

    @resource_verb.setter
    def resource_verb(self, resource_verb: ResourceVerbType):
        """Sets the resource_verb of this QueueItemType.


        :param resource_verb: The resource_verb of this QueueItemType.
        :type resource_verb: ResourceVerbType
        """

        self._resource_verb = resource_verb

    @property
    def resource_id(self) -> str:
        """Gets the resource_id of this QueueItemType.


        :return: The resource_id of this QueueItemType.
        :rtype: str
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id: str):
        """Sets the resource_id of this QueueItemType.


        :param resource_id: The resource_id of this QueueItemType.
        :type resource_id: str
        """

        self._resource_id = resource_id

    @property
    def creation_date(self) -> datetime:
        """Gets the creation_date of this QueueItemType.


        :return: The creation_date of this QueueItemType.
        :rtype: datetime
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date: datetime):
        """Sets the creation_date of this QueueItemType.


        :param creation_date: The creation_date of this QueueItemType.
        :type creation_date: datetime
        """
        if creation_date is None:
            raise ValueError("Invalid value for `creation_date`, must not be `None`")  # noqa: E501

        self._creation_date = creation_date

    @property
    def modification_date(self) -> datetime:
        """Gets the modification_date of this QueueItemType.


        :return: The modification_date of this QueueItemType.
        :rtype: datetime
        """
        return self._modification_date

    @modification_date.setter
    def modification_date(self, modification_date: datetime):
        """Sets the modification_date of this QueueItemType.


        :param modification_date: The modification_date of this QueueItemType.
        :type modification_date: datetime
        """

        self._modification_date = modification_date

    @property
    def error_code(self) -> str:
        """Gets the error_code of this QueueItemType.


        :return: The error_code of this QueueItemType.
        :rtype: str
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code: str):
        """Sets the error_code of this QueueItemType.


        :param error_code: The error_code of this QueueItemType.
        :type error_code: str
        """

        self._error_code = error_code

    @property
    def error_message(self) -> str:
        """Gets the error_message of this QueueItemType.


        :return: The error_message of this QueueItemType.
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message: str):
        """Sets the error_message of this QueueItemType.


        :param error_message: The error_message of this QueueItemType.
        :type error_message: str
        """

        self._error_message = error_message

    @property
    def status(self) -> QueueStatusType:
        """Gets the status of this QueueItemType.


        :return: The status of this QueueItemType.
        :rtype: QueueStatusType
        """
        return self._status

    @status.setter
    def status(self, status: QueueStatusType):
        """Sets the status of this QueueItemType.


        :param status: The status of this QueueItemType.
        :type status: QueueStatusType
        """

        self._status = status

    @property
    def error_detail_list(self) -> QueueItemTypeErrorDetailList:
        """Gets the error_detail_list of this QueueItemType.


        :return: The error_detail_list of this QueueItemType.
        :rtype: QueueItemTypeErrorDetailList
        """
        return self._error_detail_list

    @error_detail_list.setter
    def error_detail_list(self, error_detail_list: QueueItemTypeErrorDetailList):
        """Sets the error_detail_list of this QueueItemType.


        :param error_detail_list: The error_detail_list of this QueueItemType.
        :type error_detail_list: QueueItemTypeErrorDetailList
        """

        self._error_detail_list = error_detail_list

    @property
    def sub_item_list(self) -> QueueItemTypeSubItemList:
        """Gets the sub_item_list of this QueueItemType.


        :return: The sub_item_list of this QueueItemType.
        :rtype: QueueItemTypeSubItemList
        """
        return self._sub_item_list

    @sub_item_list.setter
    def sub_item_list(self, sub_item_list: QueueItemTypeSubItemList):
        """Sets the sub_item_list of this QueueItemType.


        :param sub_item_list: The sub_item_list of this QueueItemType.
        :type sub_item_list: QueueItemTypeSubItemList
        """

        self._sub_item_list = sub_item_list
