# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.queue_item_type import QueueItemType  # noqa: F401,E501
from swagger_server import util


class QueueItemTypeSubItemList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, sub_item: List[QueueItemType]=None):  # noqa: E501
        """QueueItemTypeSubItemList - a model defined in Swagger

        :param sub_item: The sub_item of this QueueItemTypeSubItemList.  # noqa: E501
        :type sub_item: List[QueueItemType]
        """
        self.swagger_types = {
            'sub_item': List[QueueItemType]
        }

        self.attribute_map = {
            'sub_item': 'subItem'
        }
        self._sub_item = sub_item

    @classmethod
    def from_dict(cls, dikt) -> 'QueueItemTypeSubItemList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QueueItemType_subItemList of this QueueItemTypeSubItemList.  # noqa: E501
        :rtype: QueueItemTypeSubItemList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sub_item(self) -> List[QueueItemType]:
        """Gets the sub_item of this QueueItemTypeSubItemList.


        :return: The sub_item of this QueueItemTypeSubItemList.
        :rtype: List[QueueItemType]
        """
        return self._sub_item

    @sub_item.setter
    def sub_item(self, sub_item: List[QueueItemType]):
        """Sets the sub_item of this QueueItemTypeSubItemList.


        :param sub_item: The sub_item of this QueueItemTypeSubItemList.
        :type sub_item: List[QueueItemType]
        """

        self._sub_item = sub_item
