# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.error_type import ErrorType  # noqa: F401,E501
from swagger_server import util


class QueueItemTypeErrorDetailList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error_detail: List[ErrorType]=None):  # noqa: E501
        """QueueItemTypeErrorDetailList - a model defined in Swagger

        :param error_detail: The error_detail of this QueueItemTypeErrorDetailList.  # noqa: E501
        :type error_detail: List[ErrorType]
        """
        self.swagger_types = {
            'error_detail': List[ErrorType]
        }

        self.attribute_map = {
            'error_detail': 'errorDetail'
        }
        self._error_detail = error_detail

    @classmethod
    def from_dict(cls, dikt) -> 'QueueItemTypeErrorDetailList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QueueItemType_errorDetailList of this QueueItemTypeErrorDetailList.  # noqa: E501
        :rtype: QueueItemTypeErrorDetailList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_detail(self) -> List[ErrorType]:
        """Gets the error_detail of this QueueItemTypeErrorDetailList.


        :return: The error_detail of this QueueItemTypeErrorDetailList.
        :rtype: List[ErrorType]
        """
        return self._error_detail

    @error_detail.setter
    def error_detail(self, error_detail: List[ErrorType]):
        """Sets the error_detail of this QueueItemTypeErrorDetailList.


        :param error_detail: The error_detail of this QueueItemTypeErrorDetailList.
        :type error_detail: List[ErrorType]
        """

        self._error_detail = error_detail
