# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.close_claim_cbm_type_claims import CloseClaimCBMTypeClaims  # noqa: F401,E501
from swagger_server import util


class ReopenClaimCBMType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, claims: CloseClaimCBMTypeClaims=None):  # noqa: E501
        """ReopenClaimCBMType - a model defined in Swagger

        :param claims: The claims of this ReopenClaimCBMType.  # noqa: E501
        :type claims: CloseClaimCBMTypeClaims
        """
        self.swagger_types = {
            'claims': CloseClaimCBMTypeClaims
        }

        self.attribute_map = {
            'claims': 'claims'
        }
        self._claims = claims

    @classmethod
    def from_dict(cls, dikt) -> 'ReopenClaimCBMType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReopenClaimCBMType of this ReopenClaimCBMType.  # noqa: E501
        :rtype: ReopenClaimCBMType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def claims(self) -> CloseClaimCBMTypeClaims:
        """Gets the claims of this ReopenClaimCBMType.


        :return: The claims of this ReopenClaimCBMType.
        :rtype: CloseClaimCBMTypeClaims
        """
        return self._claims

    @claims.setter
    def claims(self, claims: CloseClaimCBMTypeClaims):
        """Sets the claims of this ReopenClaimCBMType.


        :param claims: The claims of this ReopenClaimCBMType.
        :type claims: CloseClaimCBMTypeClaims
        """
        if claims is None:
            raise ValueError("Invalid value for `claims`, must not be `None`")  # noqa: E501

        self._claims = claims
