# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.reported_invoice_type import ReportedInvoiceType  # noqa: F401,E501
from swagger_server import util


class ReportedInvoicesListType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, reported_invoice: List[ReportedInvoiceType]=None):  # noqa: E501
        """ReportedInvoicesListType - a model defined in Swagger

        :param reported_invoice: The reported_invoice of this ReportedInvoicesListType.  # noqa: E501
        :type reported_invoice: List[ReportedInvoiceType]
        """
        self.swagger_types = {
            'reported_invoice': List[ReportedInvoiceType]
        }

        self.attribute_map = {
            'reported_invoice': 'reportedInvoice'
        }
        self._reported_invoice = reported_invoice

    @classmethod
    def from_dict(cls, dikt) -> 'ReportedInvoicesListType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReportedInvoicesListType of this ReportedInvoicesListType.  # noqa: E501
        :rtype: ReportedInvoicesListType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reported_invoice(self) -> List[ReportedInvoiceType]:
        """Gets the reported_invoice of this ReportedInvoicesListType.


        :return: The reported_invoice of this ReportedInvoicesListType.
        :rtype: List[ReportedInvoiceType]
        """
        return self._reported_invoice

    @reported_invoice.setter
    def reported_invoice(self, reported_invoice: List[ReportedInvoiceType]):
        """Sets the reported_invoice of this ReportedInvoicesListType.


        :param reported_invoice: The reported_invoice of this ReportedInvoicesListType.
        :type reported_invoice: List[ReportedInvoiceType]
        """

        self._reported_invoice = reported_invoice
