# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.paging_type import PagingType  # noqa: F401,E501
from swagger_server import util


class SearchInvoiceDataAreaType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, paging: PagingType=None, invoice_id: str=None, batch_id: str=None, policy_id: str=None, member_id: str=None, status: str=None, billing_provider: str=None, external_reference_id: str=None):  # noqa: E501
        """SearchInvoiceDataAreaType - a model defined in Swagger

        :param paging: The paging of this SearchInvoiceDataAreaType.  # noqa: E501
        :type paging: PagingType
        :param invoice_id: The invoice_id of this SearchInvoiceDataAreaType.  # noqa: E501
        :type invoice_id: str
        :param batch_id: The batch_id of this SearchInvoiceDataAreaType.  # noqa: E501
        :type batch_id: str
        :param policy_id: The policy_id of this SearchInvoiceDataAreaType.  # noqa: E501
        :type policy_id: str
        :param member_id: The member_id of this SearchInvoiceDataAreaType.  # noqa: E501
        :type member_id: str
        :param status: The status of this SearchInvoiceDataAreaType.  # noqa: E501
        :type status: str
        :param billing_provider: The billing_provider of this SearchInvoiceDataAreaType.  # noqa: E501
        :type billing_provider: str
        :param external_reference_id: The external_reference_id of this SearchInvoiceDataAreaType.  # noqa: E501
        :type external_reference_id: str
        """
        self.swagger_types = {
            'paging': PagingType,
            'invoice_id': str,
            'batch_id': str,
            'policy_id': str,
            'member_id': str,
            'status': str,
            'billing_provider': str,
            'external_reference_id': str
        }

        self.attribute_map = {
            'paging': 'paging',
            'invoice_id': 'invoiceId',
            'batch_id': 'batchId',
            'policy_id': 'policyId',
            'member_id': 'memberId',
            'status': 'status',
            'billing_provider': 'billingProvider',
            'external_reference_id': 'externalReferenceId'
        }
        self._paging = paging
        self._invoice_id = invoice_id
        self._batch_id = batch_id
        self._policy_id = policy_id
        self._member_id = member_id
        self._status = status
        self._billing_provider = billing_provider
        self._external_reference_id = external_reference_id

    @classmethod
    def from_dict(cls, dikt) -> 'SearchInvoiceDataAreaType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SearchInvoiceDataAreaType of this SearchInvoiceDataAreaType.  # noqa: E501
        :rtype: SearchInvoiceDataAreaType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def paging(self) -> PagingType:
        """Gets the paging of this SearchInvoiceDataAreaType.


        :return: The paging of this SearchInvoiceDataAreaType.
        :rtype: PagingType
        """
        return self._paging

    @paging.setter
    def paging(self, paging: PagingType):
        """Sets the paging of this SearchInvoiceDataAreaType.


        :param paging: The paging of this SearchInvoiceDataAreaType.
        :type paging: PagingType
        """

        self._paging = paging

    @property
    def invoice_id(self) -> str:
        """Gets the invoice_id of this SearchInvoiceDataAreaType.


        :return: The invoice_id of this SearchInvoiceDataAreaType.
        :rtype: str
        """
        return self._invoice_id

    @invoice_id.setter
    def invoice_id(self, invoice_id: str):
        """Sets the invoice_id of this SearchInvoiceDataAreaType.


        :param invoice_id: The invoice_id of this SearchInvoiceDataAreaType.
        :type invoice_id: str
        """

        self._invoice_id = invoice_id

    @property
    def batch_id(self) -> str:
        """Gets the batch_id of this SearchInvoiceDataAreaType.


        :return: The batch_id of this SearchInvoiceDataAreaType.
        :rtype: str
        """
        return self._batch_id

    @batch_id.setter
    def batch_id(self, batch_id: str):
        """Sets the batch_id of this SearchInvoiceDataAreaType.


        :param batch_id: The batch_id of this SearchInvoiceDataAreaType.
        :type batch_id: str
        """

        self._batch_id = batch_id

    @property
    def policy_id(self) -> str:
        """Gets the policy_id of this SearchInvoiceDataAreaType.


        :return: The policy_id of this SearchInvoiceDataAreaType.
        :rtype: str
        """
        return self._policy_id

    @policy_id.setter
    def policy_id(self, policy_id: str):
        """Sets the policy_id of this SearchInvoiceDataAreaType.


        :param policy_id: The policy_id of this SearchInvoiceDataAreaType.
        :type policy_id: str
        """

        self._policy_id = policy_id

    @property
    def member_id(self) -> str:
        """Gets the member_id of this SearchInvoiceDataAreaType.


        :return: The member_id of this SearchInvoiceDataAreaType.
        :rtype: str
        """
        return self._member_id

    @member_id.setter
    def member_id(self, member_id: str):
        """Sets the member_id of this SearchInvoiceDataAreaType.


        :param member_id: The member_id of this SearchInvoiceDataAreaType.
        :type member_id: str
        """

        self._member_id = member_id

    @property
    def status(self) -> str:
        """Gets the status of this SearchInvoiceDataAreaType.


        :return: The status of this SearchInvoiceDataAreaType.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this SearchInvoiceDataAreaType.


        :param status: The status of this SearchInvoiceDataAreaType.
        :type status: str
        """

        self._status = status

    @property
    def billing_provider(self) -> str:
        """Gets the billing_provider of this SearchInvoiceDataAreaType.


        :return: The billing_provider of this SearchInvoiceDataAreaType.
        :rtype: str
        """
        return self._billing_provider

    @billing_provider.setter
    def billing_provider(self, billing_provider: str):
        """Sets the billing_provider of this SearchInvoiceDataAreaType.


        :param billing_provider: The billing_provider of this SearchInvoiceDataAreaType.
        :type billing_provider: str
        """

        self._billing_provider = billing_provider

    @property
    def external_reference_id(self) -> str:
        """Gets the external_reference_id of this SearchInvoiceDataAreaType.


        :return: The external_reference_id of this SearchInvoiceDataAreaType.
        :rtype: str
        """
        return self._external_reference_id

    @external_reference_id.setter
    def external_reference_id(self, external_reference_id: str):
        """Sets the external_reference_id of this SearchInvoiceDataAreaType.


        :param external_reference_id: The external_reference_id of this SearchInvoiceDataAreaType.
        :type external_reference_id: str
        """

        self._external_reference_id = external_reference_id
