# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.search_batch_data_area_type import SearchBatchDataAreaType  # noqa: F401,E501
from swagger_server import util


class SearchBatchCBMType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, search_criteria: SearchBatchDataAreaType=None):  # noqa: E501
        """SearchBatchCBMType - a model defined in Swagger

        :param search_criteria: The search_criteria of this SearchBatchCBMType.  # noqa: E501
        :type search_criteria: SearchBatchDataAreaType
        """
        self.swagger_types = {
            'search_criteria': SearchBatchDataAreaType
        }

        self.attribute_map = {
            'search_criteria': 'searchCriteria'
        }
        self._search_criteria = search_criteria

    @classmethod
    def from_dict(cls, dikt) -> 'SearchBatchCBMType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SearchBatchCBMType of this SearchBatchCBMType.  # noqa: E501
        :rtype: SearchBatchCBMType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def search_criteria(self) -> SearchBatchDataAreaType:
        """Gets the search_criteria of this SearchBatchCBMType.


        :return: The search_criteria of this SearchBatchCBMType.
        :rtype: SearchBatchDataAreaType
        """
        return self._search_criteria

    @search_criteria.setter
    def search_criteria(self, search_criteria: SearchBatchDataAreaType):
        """Sets the search_criteria of this SearchBatchCBMType.


        :param search_criteria: The search_criteria of this SearchBatchCBMType.
        :type search_criteria: SearchBatchDataAreaType
        """
        if search_criteria is None:
            raise ValueError("Invalid value for `search_criteria`, must not be `None`")  # noqa: E501

        self._search_criteria = search_criteria
