# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SearchInvoiceReportCBMType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, run_number: int=None):  # noqa: E501
        """SearchInvoiceReportCBMType - a model defined in Swagger

        :param run_number: The run_number of this SearchInvoiceReportCBMType.  # noqa: E501
        :type run_number: int
        """
        self.swagger_types = {
            'run_number': int
        }

        self.attribute_map = {
            'run_number': 'runNumber'
        }
        self._run_number = run_number

    @classmethod
    def from_dict(cls, dikt) -> 'SearchInvoiceReportCBMType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SearchInvoiceReportCBMType of this SearchInvoiceReportCBMType.  # noqa: E501
        :rtype: SearchInvoiceReportCBMType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def run_number(self) -> int:
        """Gets the run_number of this SearchInvoiceReportCBMType.


        :return: The run_number of this SearchInvoiceReportCBMType.
        :rtype: int
        """
        return self._run_number

    @run_number.setter
    def run_number(self, run_number: int):
        """Sets the run_number of this SearchInvoiceReportCBMType.


        :param run_number: The run_number of this SearchInvoiceReportCBMType.
        :type run_number: int
        """
        if run_number is None:
            raise ValueError("Invalid value for `run_number`, must not be `None`")  # noqa: E501

        self._run_number = run_number
