# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.claims_response_type import ClaimsResponseType  # noqa: F401,E501
from swagger_server import util


class SearchClaimResponseCBMType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, claims: ClaimsResponseType=None):  # noqa: E501
        """SearchClaimResponseCBMType - a model defined in Swagger

        :param claims: The claims of this SearchClaimResponseCBMType.  # noqa: E501
        :type claims: ClaimsResponseType
        """
        self.swagger_types = {
            'claims': ClaimsResponseType
        }

        self.attribute_map = {
            'claims': 'claims'
        }
        self._claims = claims

    @classmethod
    def from_dict(cls, dikt) -> 'SearchClaimResponseCBMType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SearchClaimResponseCBMType of this SearchClaimResponseCBMType.  # noqa: E501
        :rtype: SearchClaimResponseCBMType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def claims(self) -> ClaimsResponseType:
        """Gets the claims of this SearchClaimResponseCBMType.


        :return: The claims of this SearchClaimResponseCBMType.
        :rtype: ClaimsResponseType
        """
        return self._claims

    @claims.setter
    def claims(self, claims: ClaimsResponseType):
        """Sets the claims of this SearchClaimResponseCBMType.


        :param claims: The claims of this SearchClaimResponseCBMType.
        :type claims: ClaimsResponseType
        """

        self._claims = claims
