# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.invoice_transaction_type import InvoiceTransactionType  # noqa: F401,E501
from swagger_server import util


class SearchInvoiceTransactionResponseCBMType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, invoice: List[InvoiceTransactionType]=None):  # noqa: E501
        """SearchInvoiceTransactionResponseCBMType - a model defined in Swagger

        :param invoice: The invoice of this SearchInvoiceTransactionResponseCBMType.  # noqa: E501
        :type invoice: List[InvoiceTransactionType]
        """
        self.swagger_types = {
            'invoice': List[InvoiceTransactionType]
        }

        self.attribute_map = {
            'invoice': 'invoice'
        }
        self._invoice = invoice

    @classmethod
    def from_dict(cls, dikt) -> 'SearchInvoiceTransactionResponseCBMType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SearchInvoiceTransactionResponseCBMType of this SearchInvoiceTransactionResponseCBMType.  # noqa: E501
        :rtype: SearchInvoiceTransactionResponseCBMType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def invoice(self) -> List[InvoiceTransactionType]:
        """Gets the invoice of this SearchInvoiceTransactionResponseCBMType.


        :return: The invoice of this SearchInvoiceTransactionResponseCBMType.
        :rtype: List[InvoiceTransactionType]
        """
        return self._invoice

    @invoice.setter
    def invoice(self, invoice: List[InvoiceTransactionType]):
        """Sets the invoice of this SearchInvoiceTransactionResponseCBMType.


        :param invoice: The invoice of this SearchInvoiceTransactionResponseCBMType.
        :type invoice: List[InvoiceTransactionType]
        """

        self._invoice = invoice
