# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.invoice_report_type import InvoiceReportType  # noqa: F401,E501
from swagger_server import util


class SearchInvoiceReportResponseCBMType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, invoice_report: InvoiceReportType=None):  # noqa: E501
        """SearchInvoiceReportResponseCBMType - a model defined in Swagger

        :param invoice_report: The invoice_report of this SearchInvoiceReportResponseCBMType.  # noqa: E501
        :type invoice_report: InvoiceReportType
        """
        self.swagger_types = {
            'invoice_report': InvoiceReportType
        }

        self.attribute_map = {
            'invoice_report': 'invoiceReport'
        }
        self._invoice_report = invoice_report

    @classmethod
    def from_dict(cls, dikt) -> 'SearchInvoiceReportResponseCBMType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SearchInvoiceReportResponseCBMType of this SearchInvoiceReportResponseCBMType.  # noqa: E501
        :rtype: SearchInvoiceReportResponseCBMType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def invoice_report(self) -> InvoiceReportType:
        """Gets the invoice_report of this SearchInvoiceReportResponseCBMType.


        :return: The invoice_report of this SearchInvoiceReportResponseCBMType.
        :rtype: InvoiceReportType
        """
        return self._invoice_report

    @invoice_report.setter
    def invoice_report(self, invoice_report: InvoiceReportType):
        """Sets the invoice_report of this SearchInvoiceReportResponseCBMType.


        :param invoice_report: The invoice_report of this SearchInvoiceReportResponseCBMType.
        :type invoice_report: InvoiceReportType
        """

        self._invoice_report = invoice_report
