# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.paging_type import PagingType  # noqa: F401,E501
from swagger_server import util


class SearchClaimDataAreaType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, paging: PagingType=None, policy_id: str=None, member_id: str=None, claim_id: int=None):  # noqa: E501
        """SearchClaimDataAreaType - a model defined in Swagger

        :param paging: The paging of this SearchClaimDataAreaType.  # noqa: E501
        :type paging: PagingType
        :param policy_id: The policy_id of this SearchClaimDataAreaType.  # noqa: E501
        :type policy_id: str
        :param member_id: The member_id of this SearchClaimDataAreaType.  # noqa: E501
        :type member_id: str
        :param claim_id: The claim_id of this SearchClaimDataAreaType.  # noqa: E501
        :type claim_id: int
        """
        self.swagger_types = {
            'paging': PagingType,
            'policy_id': str,
            'member_id': str,
            'claim_id': int
        }

        self.attribute_map = {
            'paging': 'paging',
            'policy_id': 'policyId',
            'member_id': 'memberId',
            'claim_id': 'claimId'
        }
        self._paging = paging
        self._policy_id = policy_id
        self._member_id = member_id
        self._claim_id = claim_id

    @classmethod
    def from_dict(cls, dikt) -> 'SearchClaimDataAreaType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SearchClaimDataAreaType of this SearchClaimDataAreaType.  # noqa: E501
        :rtype: SearchClaimDataAreaType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def paging(self) -> PagingType:
        """Gets the paging of this SearchClaimDataAreaType.


        :return: The paging of this SearchClaimDataAreaType.
        :rtype: PagingType
        """
        return self._paging

    @paging.setter
    def paging(self, paging: PagingType):
        """Sets the paging of this SearchClaimDataAreaType.


        :param paging: The paging of this SearchClaimDataAreaType.
        :type paging: PagingType
        """

        self._paging = paging

    @property
    def policy_id(self) -> str:
        """Gets the policy_id of this SearchClaimDataAreaType.


        :return: The policy_id of this SearchClaimDataAreaType.
        :rtype: str
        """
        return self._policy_id

    @policy_id.setter
    def policy_id(self, policy_id: str):
        """Sets the policy_id of this SearchClaimDataAreaType.


        :param policy_id: The policy_id of this SearchClaimDataAreaType.
        :type policy_id: str
        """

        self._policy_id = policy_id

    @property
    def member_id(self) -> str:
        """Gets the member_id of this SearchClaimDataAreaType.


        :return: The member_id of this SearchClaimDataAreaType.
        :rtype: str
        """
        return self._member_id

    @member_id.setter
    def member_id(self, member_id: str):
        """Sets the member_id of this SearchClaimDataAreaType.


        :param member_id: The member_id of this SearchClaimDataAreaType.
        :type member_id: str
        """

        self._member_id = member_id

    @property
    def claim_id(self) -> int:
        """Gets the claim_id of this SearchClaimDataAreaType.


        :return: The claim_id of this SearchClaimDataAreaType.
        :rtype: int
        """
        return self._claim_id

    @claim_id.setter
    def claim_id(self, claim_id: int):
        """Sets the claim_id of this SearchClaimDataAreaType.


        :param claim_id: The claim_id of this SearchClaimDataAreaType.
        :type claim_id: int
        """

        self._claim_id = claim_id
