# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.paging_type import PagingType  # noqa: F401,E501
from swagger_server import util


class SearchClaimCBMType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, paging: PagingType=None, insurance_company_nbr: int=None, claim_nbr: int=None, policy_nbr: int=None, policy_external_reference_id: str=None, member_nbr: int=None, member_external_reference_id: str=None, member_first_name: str=None, member_middle_name: str=None, member_last_name: str=None, claim_type_id: str=None, claim_status_id: str=None, occurance_date_from: datetime=None, occurance_date_to: datetime=None, claim_external_reference_id: str=None):  # noqa: E501
        """SearchClaimCBMType - a model defined in Swagger

        :param paging: The paging of this SearchClaimCBMType.  # noqa: E501
        :type paging: PagingType
        :param insurance_company_nbr: The insurance_company_nbr of this SearchClaimCBMType.  # noqa: E501
        :type insurance_company_nbr: int
        :param claim_nbr: The claim_nbr of this SearchClaimCBMType.  # noqa: E501
        :type claim_nbr: int
        :param policy_nbr: The policy_nbr of this SearchClaimCBMType.  # noqa: E501
        :type policy_nbr: int
        :param policy_external_reference_id: The policy_external_reference_id of this SearchClaimCBMType.  # noqa: E501
        :type policy_external_reference_id: str
        :param member_nbr: The member_nbr of this SearchClaimCBMType.  # noqa: E501
        :type member_nbr: int
        :param member_external_reference_id: The member_external_reference_id of this SearchClaimCBMType.  # noqa: E501
        :type member_external_reference_id: str
        :param member_first_name: The member_first_name of this SearchClaimCBMType.  # noqa: E501
        :type member_first_name: str
        :param member_middle_name: The member_middle_name of this SearchClaimCBMType.  # noqa: E501
        :type member_middle_name: str
        :param member_last_name: The member_last_name of this SearchClaimCBMType.  # noqa: E501
        :type member_last_name: str
        :param claim_type_id: The claim_type_id of this SearchClaimCBMType.  # noqa: E501
        :type claim_type_id: str
        :param claim_status_id: The claim_status_id of this SearchClaimCBMType.  # noqa: E501
        :type claim_status_id: str
        :param occurance_date_from: The occurance_date_from of this SearchClaimCBMType.  # noqa: E501
        :type occurance_date_from: datetime
        :param occurance_date_to: The occurance_date_to of this SearchClaimCBMType.  # noqa: E501
        :type occurance_date_to: datetime
        :param claim_external_reference_id: The claim_external_reference_id of this SearchClaimCBMType.  # noqa: E501
        :type claim_external_reference_id: str
        """
        self.swagger_types = {
            'paging': PagingType,
            'insurance_company_nbr': int,
            'claim_nbr': int,
            'policy_nbr': int,
            'policy_external_reference_id': str,
            'member_nbr': int,
            'member_external_reference_id': str,
            'member_first_name': str,
            'member_middle_name': str,
            'member_last_name': str,
            'claim_type_id': str,
            'claim_status_id': str,
            'occurance_date_from': datetime,
            'occurance_date_to': datetime,
            'claim_external_reference_id': str
        }

        self.attribute_map = {
            'paging': 'paging',
            'insurance_company_nbr': 'insuranceCompanyNbr',
            'claim_nbr': 'claimNbr',
            'policy_nbr': 'policyNbr',
            'policy_external_reference_id': 'policyExternalReferenceId',
            'member_nbr': 'memberNbr',
            'member_external_reference_id': 'memberExternalReferenceId',
            'member_first_name': 'memberFirstName',
            'member_middle_name': 'memberMiddleName',
            'member_last_name': 'memberLastName',
            'claim_type_id': 'claimTypeId',
            'claim_status_id': 'claimStatusId',
            'occurance_date_from': 'occuranceDateFrom',
            'occurance_date_to': 'occuranceDateTo',
            'claim_external_reference_id': 'claimExternalReferenceId'
        }
        self._paging = paging
        self._insurance_company_nbr = insurance_company_nbr
        self._claim_nbr = claim_nbr
        self._policy_nbr = policy_nbr
        self._policy_external_reference_id = policy_external_reference_id
        self._member_nbr = member_nbr
        self._member_external_reference_id = member_external_reference_id
        self._member_first_name = member_first_name
        self._member_middle_name = member_middle_name
        self._member_last_name = member_last_name
        self._claim_type_id = claim_type_id
        self._claim_status_id = claim_status_id
        self._occurance_date_from = occurance_date_from
        self._occurance_date_to = occurance_date_to
        self._claim_external_reference_id = claim_external_reference_id

    @classmethod
    def from_dict(cls, dikt) -> 'SearchClaimCBMType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SearchClaimCBMType of this SearchClaimCBMType.  # noqa: E501
        :rtype: SearchClaimCBMType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def paging(self) -> PagingType:
        """Gets the paging of this SearchClaimCBMType.


        :return: The paging of this SearchClaimCBMType.
        :rtype: PagingType
        """
        return self._paging

    @paging.setter
    def paging(self, paging: PagingType):
        """Sets the paging of this SearchClaimCBMType.


        :param paging: The paging of this SearchClaimCBMType.
        :type paging: PagingType
        """

        self._paging = paging

    @property
    def insurance_company_nbr(self) -> int:
        """Gets the insurance_company_nbr of this SearchClaimCBMType.


        :return: The insurance_company_nbr of this SearchClaimCBMType.
        :rtype: int
        """
        return self._insurance_company_nbr

    @insurance_company_nbr.setter
    def insurance_company_nbr(self, insurance_company_nbr: int):
        """Sets the insurance_company_nbr of this SearchClaimCBMType.


        :param insurance_company_nbr: The insurance_company_nbr of this SearchClaimCBMType.
        :type insurance_company_nbr: int
        """
        if insurance_company_nbr is None:
            raise ValueError("Invalid value for `insurance_company_nbr`, must not be `None`")  # noqa: E501

        self._insurance_company_nbr = insurance_company_nbr

    @property
    def claim_nbr(self) -> int:
        """Gets the claim_nbr of this SearchClaimCBMType.


        :return: The claim_nbr of this SearchClaimCBMType.
        :rtype: int
        """
        return self._claim_nbr

    @claim_nbr.setter
    def claim_nbr(self, claim_nbr: int):
        """Sets the claim_nbr of this SearchClaimCBMType.


        :param claim_nbr: The claim_nbr of this SearchClaimCBMType.
        :type claim_nbr: int
        """

        self._claim_nbr = claim_nbr

    @property
    def policy_nbr(self) -> int:
        """Gets the policy_nbr of this SearchClaimCBMType.


        :return: The policy_nbr of this SearchClaimCBMType.
        :rtype: int
        """
        return self._policy_nbr

    @policy_nbr.setter
    def policy_nbr(self, policy_nbr: int):
        """Sets the policy_nbr of this SearchClaimCBMType.


        :param policy_nbr: The policy_nbr of this SearchClaimCBMType.
        :type policy_nbr: int
        """

        self._policy_nbr = policy_nbr

    @property
    def policy_external_reference_id(self) -> str:
        """Gets the policy_external_reference_id of this SearchClaimCBMType.


        :return: The policy_external_reference_id of this SearchClaimCBMType.
        :rtype: str
        """
        return self._policy_external_reference_id

    @policy_external_reference_id.setter
    def policy_external_reference_id(self, policy_external_reference_id: str):
        """Sets the policy_external_reference_id of this SearchClaimCBMType.


        :param policy_external_reference_id: The policy_external_reference_id of this SearchClaimCBMType.
        :type policy_external_reference_id: str
        """

        self._policy_external_reference_id = policy_external_reference_id

    @property
    def member_nbr(self) -> int:
        """Gets the member_nbr of this SearchClaimCBMType.


        :return: The member_nbr of this SearchClaimCBMType.
        :rtype: int
        """
        return self._member_nbr

    @member_nbr.setter
    def member_nbr(self, member_nbr: int):
        """Sets the member_nbr of this SearchClaimCBMType.


        :param member_nbr: The member_nbr of this SearchClaimCBMType.
        :type member_nbr: int
        """

        self._member_nbr = member_nbr

    @property
    def member_external_reference_id(self) -> str:
        """Gets the member_external_reference_id of this SearchClaimCBMType.


        :return: The member_external_reference_id of this SearchClaimCBMType.
        :rtype: str
        """
        return self._member_external_reference_id

    @member_external_reference_id.setter
    def member_external_reference_id(self, member_external_reference_id: str):
        """Sets the member_external_reference_id of this SearchClaimCBMType.


        :param member_external_reference_id: The member_external_reference_id of this SearchClaimCBMType.
        :type member_external_reference_id: str
        """

        self._member_external_reference_id = member_external_reference_id

    @property
    def member_first_name(self) -> str:
        """Gets the member_first_name of this SearchClaimCBMType.


        :return: The member_first_name of this SearchClaimCBMType.
        :rtype: str
        """
        return self._member_first_name

    @member_first_name.setter
    def member_first_name(self, member_first_name: str):
        """Sets the member_first_name of this SearchClaimCBMType.


        :param member_first_name: The member_first_name of this SearchClaimCBMType.
        :type member_first_name: str
        """

        self._member_first_name = member_first_name

    @property
    def member_middle_name(self) -> str:
        """Gets the member_middle_name of this SearchClaimCBMType.


        :return: The member_middle_name of this SearchClaimCBMType.
        :rtype: str
        """
        return self._member_middle_name

    @member_middle_name.setter
    def member_middle_name(self, member_middle_name: str):
        """Sets the member_middle_name of this SearchClaimCBMType.


        :param member_middle_name: The member_middle_name of this SearchClaimCBMType.
        :type member_middle_name: str
        """

        self._member_middle_name = member_middle_name

    @property
    def member_last_name(self) -> str:
        """Gets the member_last_name of this SearchClaimCBMType.


        :return: The member_last_name of this SearchClaimCBMType.
        :rtype: str
        """
        return self._member_last_name

    @member_last_name.setter
    def member_last_name(self, member_last_name: str):
        """Sets the member_last_name of this SearchClaimCBMType.


        :param member_last_name: The member_last_name of this SearchClaimCBMType.
        :type member_last_name: str
        """

        self._member_last_name = member_last_name

    @property
    def claim_type_id(self) -> str:
        """Gets the claim_type_id of this SearchClaimCBMType.


        :return: The claim_type_id of this SearchClaimCBMType.
        :rtype: str
        """
        return self._claim_type_id

    @claim_type_id.setter
    def claim_type_id(self, claim_type_id: str):
        """Sets the claim_type_id of this SearchClaimCBMType.


        :param claim_type_id: The claim_type_id of this SearchClaimCBMType.
        :type claim_type_id: str
        """

        self._claim_type_id = claim_type_id

    @property
    def claim_status_id(self) -> str:
        """Gets the claim_status_id of this SearchClaimCBMType.


        :return: The claim_status_id of this SearchClaimCBMType.
        :rtype: str
        """
        return self._claim_status_id

    @claim_status_id.setter
    def claim_status_id(self, claim_status_id: str):
        """Sets the claim_status_id of this SearchClaimCBMType.


        :param claim_status_id: The claim_status_id of this SearchClaimCBMType.
        :type claim_status_id: str
        """

        self._claim_status_id = claim_status_id

    @property
    def occurance_date_from(self) -> datetime:
        """Gets the occurance_date_from of this SearchClaimCBMType.


        :return: The occurance_date_from of this SearchClaimCBMType.
        :rtype: datetime
        """
        return self._occurance_date_from

    @occurance_date_from.setter
    def occurance_date_from(self, occurance_date_from: datetime):
        """Sets the occurance_date_from of this SearchClaimCBMType.


        :param occurance_date_from: The occurance_date_from of this SearchClaimCBMType.
        :type occurance_date_from: datetime
        """

        self._occurance_date_from = occurance_date_from

    @property
    def occurance_date_to(self) -> datetime:
        """Gets the occurance_date_to of this SearchClaimCBMType.


        :return: The occurance_date_to of this SearchClaimCBMType.
        :rtype: datetime
        """
        return self._occurance_date_to

    @occurance_date_to.setter
    def occurance_date_to(self, occurance_date_to: datetime):
        """Sets the occurance_date_to of this SearchClaimCBMType.


        :param occurance_date_to: The occurance_date_to of this SearchClaimCBMType.
        :type occurance_date_to: datetime
        """

        self._occurance_date_to = occurance_date_to

    @property
    def claim_external_reference_id(self) -> str:
        """Gets the claim_external_reference_id of this SearchClaimCBMType.


        :return: The claim_external_reference_id of this SearchClaimCBMType.
        :rtype: str
        """
        return self._claim_external_reference_id

    @claim_external_reference_id.setter
    def claim_external_reference_id(self, claim_external_reference_id: str):
        """Sets the claim_external_reference_id of this SearchClaimCBMType.


        :param claim_external_reference_id: The claim_external_reference_id of this SearchClaimCBMType.
        :type claim_external_reference_id: str
        """

        self._claim_external_reference_id = claim_external_reference_id
